#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSSistemaPuntoVentaClinico.Data.Conexiones.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaFacturacionMedico")]
	public partial class BDCajaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDCajaDataContext() : 
				base(global::DSSistemaPuntoVentaClinico.Data.Properties.Settings.Default.SistemaFacturacionMedicoConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public BDCajaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDCajaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDCajaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDCajaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_BUSCA_MONEDA")]
		public ISingleResult<SP_BUSCA_MONEDAResult> SP_BUSCA_MONEDA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMoneda", DbType="Decimal(20,0)")] System.Nullable<decimal> idMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoMoneda", DbType="VarChar(100)")] string codigoMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMoneda, codigoMoneda, descripcion, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_MONEDAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_MANTENIMIENTO_MONEDAS")]
		public ISingleResult<SP_MANTENIMIENTO_MONEDASResult> SP_MANTENIMIENTO_MONEDAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMoneda", DbType="Decimal(20,0)")] System.Nullable<decimal> idMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoMoneda", DbType="VarChar(100)")] string codigoMoneda, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sigla", DbType="VarChar(100)")] string sigla, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tasa", DbType="Decimal(20,2)")] System.Nullable<decimal> tasa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PorDefault", DbType="Bit")] System.Nullable<bool> porDefault, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Idusuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idusuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMoneda, codigoMoneda, descripcion, sigla, tasa, estatus, porDefault, idusuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_MONEDASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_BUSCA_CAJA")]
		public ISingleResult<SP_BUSCA_CAJAResult> SP_BUSCA_CAJA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCaja", DbType="Decimal(20,0)")] System.Nullable<decimal> idCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoCaja", DbType="VarChar(100)")] string codigoCaja)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCaja, codigoCaja);
			return ((ISingleResult<SP_BUSCA_CAJAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_MANTENIMIENTO_CAJA")]
		public ISingleResult<SP_MANTENIMIENTO_CAJAResult> SP_MANTENIMIENTO_CAJA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCaja", DbType="Decimal(20,0)")] System.Nullable<decimal> idCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoCaja", DbType="VarChar(100)")] string codigoCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoActual", DbType="Decimal(20,2)")] System.Nullable<decimal> montoActual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCaja, codigoCaja, descripcion, montoActual, estatus, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_CAJAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_MANTENIMIENTO_HISTORIAL_CAJA")]
		public ISingleResult<SP_MANTENIMIENTO_HISTORIAL_CAJAResult> SP_MANTENIMIENTO_HISTORIAL_CAJA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdistorialCaja", DbType="Decimal(20,0)")] System.Nullable<decimal> idistorialCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCaja", DbType="Decimal(20,0)")] System.Nullable<decimal> idCaja, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Monto", DbType="Decimal(20,2)")] System.Nullable<decimal> monto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Concepto", DbType="VarChar(8000)")] string concepto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroReferencia", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroReferencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoPago", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoPago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idistorialCaja, idCaja, monto, concepto, idUsuario, numeroReferencia, idTipoPago, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_HISTORIAL_CAJAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_MOSTRAR_HISTORIAL_CAJA")]
		public ISingleResult<SP_MOSTRAR_HISTORIAL_CAJAResult> SP_MOSTRAR_HISTORIAL_CAJA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaDesde", DbType="Date")] System.Nullable<System.DateTime> fechaDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaHasta", DbType="Date")] System.Nullable<System.DateTime> fechaHasta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fechaDesde, fechaHasta);
			return ((ISingleResult<SP_MOSTRAR_HISTORIAL_CAJAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Caja.SP_BUSCAR_PAGOS_FACTURAS")]
		public ISingleResult<SP_BUSCAR_PAGOS_FACTURASResult> SP_BUSCAR_PAGOS_FACTURAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRecibo", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroRecibo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNC", DbType="VarChar(100)")] string rNC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaPagoDesde", DbType="Date")] System.Nullable<System.DateTime> fechaPagoDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaPagoHasta", DbType="Date")] System.Nullable<System.DateTime> fechaPagoHasta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroRecibo, numeroFactura, rNC, fechaPagoDesde, fechaPagoHasta);
			return ((ISingleResult<SP_BUSCAR_PAGOS_FACTURASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Cobros.SP_APLICAR_PAGOS_FACTURAS")]
		public ISingleResult<SP_APLICAR_PAGOS_FACTURASResult> SP_APLICAR_PAGOS_FACTURAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRecibo", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroRecibo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPaciente", DbType="Decimal(20,0)")] System.Nullable<decimal> idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Concepto", DbType="VarChar(8000)")] string concepto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Monto", DbType="Decimal(20,2)")] System.Nullable<decimal> monto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Balance", DbType="Decimal(20,2)")] System.Nullable<decimal> balance, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pendiente", DbType="Decimal(20,2)")] System.Nullable<decimal> pendiente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoPago", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoPago, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cambio", DbType="Decimal(20,2)")] System.Nullable<decimal> cambio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numeroRecibo, numeroFactura, idPaciente, idUsuario, concepto, monto, balance, pendiente, idTipoPago, cambio, accion);
			return ((ISingleResult<SP_APLICAR_PAGOS_FACTURASResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_BUSCA_MONEDAResult
	{
		
		private System.Nullable<decimal> _IdMoneda;
		
		private string _CodigoMoneda;
		
		private string _Moneda;
		
		private string _Sigla;
		
		private System.Nullable<decimal> _Tasa;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<bool> _PorDefault0;
		
		private string _PorDefecto;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_MONEDAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMoneda", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMoneda
		{
			get
			{
				return this._IdMoneda;
			}
			set
			{
				if ((this._IdMoneda != value))
				{
					this._IdMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMoneda", DbType="VarChar(100)")]
		public string CodigoMoneda
		{
			get
			{
				return this._CodigoMoneda;
			}
			set
			{
				if ((this._CodigoMoneda != value))
				{
					this._CodigoMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moneda", DbType="VarChar(100)")]
		public string Moneda
		{
			get
			{
				return this._Moneda;
			}
			set
			{
				if ((this._Moneda != value))
				{
					this._Moneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sigla", DbType="VarChar(100)")]
		public string Sigla
		{
			get
			{
				return this._Sigla;
			}
			set
			{
				if ((this._Sigla != value))
				{
					this._Sigla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tasa", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Tasa
		{
			get
			{
				return this._Tasa;
			}
			set
			{
				if ((this._Tasa != value))
				{
					this._Tasa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8)")]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorDefault0", DbType="Bit")]
		public System.Nullable<bool> PorDefault0
		{
			get
			{
				return this._PorDefault0;
			}
			set
			{
				if ((this._PorDefault0 != value))
				{
					this._PorDefault0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorDefecto", DbType="VarChar(2)")]
		public string PorDefecto
		{
			get
			{
				return this._PorDefecto;
			}
			set
			{
				if ((this._PorDefecto != value))
				{
					this._PorDefecto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_MONEDASResult
	{
		
		private System.Nullable<decimal> _IdMoneda;
		
		private string _CodigoMoneda;
		
		private string _Descripcion;
		
		private string _Sigla;
		
		private System.Nullable<decimal> _Tasa;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<bool> _PorDefault;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_MONEDASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMoneda", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMoneda
		{
			get
			{
				return this._IdMoneda;
			}
			set
			{
				if ((this._IdMoneda != value))
				{
					this._IdMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMoneda", DbType="VarChar(100)")]
		public string CodigoMoneda
		{
			get
			{
				return this._CodigoMoneda;
			}
			set
			{
				if ((this._CodigoMoneda != value))
				{
					this._CodigoMoneda = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sigla", DbType="VarChar(100)")]
		public string Sigla
		{
			get
			{
				return this._Sigla;
			}
			set
			{
				if ((this._Sigla != value))
				{
					this._Sigla = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tasa", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Tasa
		{
			get
			{
				return this._Tasa;
			}
			set
			{
				if ((this._Tasa != value))
				{
					this._Tasa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorDefault", DbType="Bit")]
		public System.Nullable<bool> PorDefault
		{
			get
			{
				return this._PorDefault;
			}
			set
			{
				if ((this._PorDefault != value))
				{
					this._PorDefault = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_CAJAResult
	{
		
		private System.Nullable<decimal> _IdCaja;
		
		private string _CodigoCaja;
		
		private string _Descripcion;
		
		private System.Nullable<decimal> _MontoActual;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		public SP_BUSCA_CAJAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaja", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCaja
		{
			get
			{
				return this._IdCaja;
			}
			set
			{
				if ((this._IdCaja != value))
				{
					this._IdCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCaja", DbType="VarChar(100)")]
		public string CodigoCaja
		{
			get
			{
				return this._CodigoCaja;
			}
			set
			{
				if ((this._CodigoCaja != value))
				{
					this._CodigoCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoActual", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoActual
		{
			get
			{
				return this._MontoActual;
			}
			set
			{
				if ((this._MontoActual != value))
				{
					this._MontoActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(7)")]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_CAJAResult
	{
		
		private System.Nullable<decimal> _IdCaja;
		
		private string _CodigoCaja;
		
		private string _Descripcion;
		
		private System.Nullable<decimal> _MontoActual;
		
		private System.Nullable<bool> _Estatus;
		
		public SP_MANTENIMIENTO_CAJAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaja", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCaja
		{
			get
			{
				return this._IdCaja;
			}
			set
			{
				if ((this._IdCaja != value))
				{
					this._IdCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCaja", DbType="VarChar(100)")]
		public string CodigoCaja
		{
			get
			{
				return this._CodigoCaja;
			}
			set
			{
				if ((this._CodigoCaja != value))
				{
					this._CodigoCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoActual", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoActual
		{
			get
			{
				return this._MontoActual;
			}
			set
			{
				if ((this._MontoActual != value))
				{
					this._MontoActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_HISTORIAL_CAJAResult
	{
		
		private System.Nullable<decimal> _IdistorialCaja;
		
		private System.Nullable<decimal> _IdCaja;
		
		private System.Nullable<decimal> _Monto;
		
		private string _Concepto;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private System.Nullable<decimal> _IdUsuario;
		
		private System.Nullable<decimal> _NumeroReferencia;
		
		private System.Nullable<decimal> _IdTipoPago;
		
		public SP_MANTENIMIENTO_HISTORIAL_CAJAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdistorialCaja", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdistorialCaja
		{
			get
			{
				return this._IdistorialCaja;
			}
			set
			{
				if ((this._IdistorialCaja != value))
				{
					this._IdistorialCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaja", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCaja
		{
			get
			{
				return this._IdCaja;
			}
			set
			{
				if ((this._IdCaja != value))
				{
					this._IdCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(8000)")]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this._Concepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroReferencia", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroReferencia
		{
			get
			{
				return this._NumeroReferencia;
			}
			set
			{
				if ((this._NumeroReferencia != value))
				{
					this._NumeroReferencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoPago
		{
			get
			{
				return this._IdTipoPago;
			}
			set
			{
				if ((this._IdTipoPago != value))
				{
					this._IdTipoPago = value;
				}
			}
		}
	}
	
	public partial class SP_MOSTRAR_HISTORIAL_CAJAResult
	{
		
		private decimal _IdistorialCaja;
		
		private System.Nullable<decimal> _IdCaja;
		
		private System.Nullable<int> _CantidadFacturado;
		
		private System.Nullable<int> _Anuladas;
		
		private System.Nullable<int> _TotalCantidadFacturado;
		
		private System.Nullable<int> _CantidadCotizaciones;
		
		private System.Nullable<int> _CantidadCirugiasProgramadas;
		
		private string _Caja;
		
		private System.Nullable<decimal> _Monto;
		
		private string _Concepto;
		
		private System.Nullable<System.DateTime> _Fecha0;
		
		private string _Fecha;
		
		private System.Nullable<decimal> _IdUsuario;
		
		private string _CreadoPor;
		
		private System.Nullable<decimal> _NumeroReferencia;
		
		private System.Nullable<decimal> _IdTipoPago;
		
		private string _TipoPago;
		
		public SP_MOSTRAR_HISTORIAL_CAJAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdistorialCaja", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdistorialCaja
		{
			get
			{
				return this._IdistorialCaja;
			}
			set
			{
				if ((this._IdistorialCaja != value))
				{
					this._IdistorialCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCaja", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCaja
		{
			get
			{
				return this._IdCaja;
			}
			set
			{
				if ((this._IdCaja != value))
				{
					this._IdCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadFacturado", DbType="Int")]
		public System.Nullable<int> CantidadFacturado
		{
			get
			{
				return this._CantidadFacturado;
			}
			set
			{
				if ((this._CantidadFacturado != value))
				{
					this._CantidadFacturado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anuladas", DbType="Int")]
		public System.Nullable<int> Anuladas
		{
			get
			{
				return this._Anuladas;
			}
			set
			{
				if ((this._Anuladas != value))
				{
					this._Anuladas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalCantidadFacturado", DbType="Int")]
		public System.Nullable<int> TotalCantidadFacturado
		{
			get
			{
				return this._TotalCantidadFacturado;
			}
			set
			{
				if ((this._TotalCantidadFacturado != value))
				{
					this._TotalCantidadFacturado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadCotizaciones", DbType="Int")]
		public System.Nullable<int> CantidadCotizaciones
		{
			get
			{
				return this._CantidadCotizaciones;
			}
			set
			{
				if ((this._CantidadCotizaciones != value))
				{
					this._CantidadCotizaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadCirugiasProgramadas", DbType="Int")]
		public System.Nullable<int> CantidadCirugiasProgramadas
		{
			get
			{
				return this._CantidadCirugiasProgramadas;
			}
			set
			{
				if ((this._CantidadCirugiasProgramadas != value))
				{
					this._CantidadCirugiasProgramadas = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caja", DbType="VarChar(100)")]
		public string Caja
		{
			get
			{
				return this._Caja;
			}
			set
			{
				if ((this._Caja != value))
				{
					this._Caja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(8000)")]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this._Concepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha0", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha0
		{
			get
			{
				return this._Fecha0;
			}
			set
			{
				if ((this._Fecha0 != value))
				{
					this._Fecha0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(30)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroReferencia", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroReferencia
		{
			get
			{
				return this._NumeroReferencia;
			}
			set
			{
				if ((this._NumeroReferencia != value))
				{
					this._NumeroReferencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoPago
		{
			get
			{
				return this._IdTipoPago;
			}
			set
			{
				if ((this._IdTipoPago != value))
				{
					this._IdTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoPago", DbType="VarChar(100)")]
		public string TipoPago
		{
			get
			{
				return this._TipoPago;
			}
			set
			{
				if ((this._TipoPago != value))
				{
					this._TipoPago = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCAR_PAGOS_FACTURASResult
	{
		
		private System.Nullable<decimal> _NumeroRecibo;
		
		private System.Nullable<decimal> _PagandoA;
		
		private string _NombrePaciente;
		
		private string _NumeroIdentificacion;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private string _Email;
		
		private string _FechaPago;
		
		private System.Nullable<decimal> _MontoFactura;
		
		private System.Nullable<decimal> _MontoPagado;
		
		private System.Nullable<decimal> _Balance;
		
		private string _Concepto;
		
		private System.Nullable<decimal> _IdTipoPago;
		
		private string _TipoPago;
		
		private System.Nullable<decimal> _IdUsuario;
		
		private string _CreadoPor;
		
		public SP_BUSCAR_PAGOS_FACTURASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroRecibo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroRecibo
		{
			get
			{
				return this._NumeroRecibo;
			}
			set
			{
				if ((this._NumeroRecibo != value))
				{
					this._NumeroRecibo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PagandoA", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> PagandoA
		{
			get
			{
				return this._PagandoA;
			}
			set
			{
				if ((this._PagandoA != value))
				{
					this._PagandoA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePaciente", DbType="VarChar(100)")]
		public string NombrePaciente
		{
			get
			{
				return this._NombrePaciente;
			}
			set
			{
				if ((this._NombrePaciente != value))
				{
					this._NombrePaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroIdentificacion", DbType="VarChar(100)")]
		public string NumeroIdentificacion
		{
			get
			{
				return this._NumeroIdentificacion;
			}
			set
			{
				if ((this._NumeroIdentificacion != value))
				{
					this._NumeroIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(30)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPago", DbType="NVarChar(30)")]
		public string FechaPago
		{
			get
			{
				return this._FechaPago;
			}
			set
			{
				if ((this._FechaPago != value))
				{
					this._FechaPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoFactura", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoFactura
		{
			get
			{
				return this._MontoFactura;
			}
			set
			{
				if ((this._MontoFactura != value))
				{
					this._MontoFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPagado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoPagado
		{
			get
			{
				return this._MontoPagado;
			}
			set
			{
				if ((this._MontoPagado != value))
				{
					this._MontoPagado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(8000)")]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this._Concepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoPago
		{
			get
			{
				return this._IdTipoPago;
			}
			set
			{
				if ((this._IdTipoPago != value))
				{
					this._IdTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoPago", DbType="VarChar(100)")]
		public string TipoPago
		{
			get
			{
				return this._TipoPago;
			}
			set
			{
				if ((this._TipoPago != value))
				{
					this._TipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
	}
	
	public partial class SP_APLICAR_PAGOS_FACTURASResult
	{
		
		private System.Nullable<decimal> _NumeroRecibo;
		
		private System.Nullable<decimal> _NumeroFactura;
		
		private System.Nullable<decimal> _IdPaciente;
		
		private System.Nullable<decimal> _IdUsuario;
		
		private string _Concepto;
		
		private System.Nullable<decimal> _Monto;
		
		private System.Nullable<decimal> _Balance;
		
		private System.Nullable<decimal> _Pendiente;
		
		private System.Nullable<decimal> _IdTipoPago;
		
		private System.Nullable<decimal> _Cambio;
		
		private System.Nullable<System.DateTime> _FechaPago;
		
		public SP_APLICAR_PAGOS_FACTURASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroRecibo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroRecibo
		{
			get
			{
				return this._NumeroRecibo;
			}
			set
			{
				if ((this._NumeroRecibo != value))
				{
					this._NumeroRecibo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this._NumeroFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPaciente", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdPaciente
		{
			get
			{
				return this._IdPaciente;
			}
			set
			{
				if ((this._IdPaciente != value))
				{
					this._IdPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(8000)")]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this._Concepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pendiente", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Pendiente
		{
			get
			{
				return this._Pendiente;
			}
			set
			{
				if ((this._Pendiente != value))
				{
					this._Pendiente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoPago", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoPago
		{
			get
			{
				return this._IdTipoPago;
			}
			set
			{
				if ((this._IdTipoPago != value))
				{
					this._IdTipoPago = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cambio", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Cambio
		{
			get
			{
				return this._Cambio;
			}
			set
			{
				if ((this._Cambio != value))
				{
					this._Cambio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaPago", DbType="Date")]
		public System.Nullable<System.DateTime> FechaPago
		{
			get
			{
				return this._FechaPago;
			}
			set
			{
				if ((this._FechaPago != value))
				{
					this._FechaPago = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
