<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaFacturacionMedico" Class="BDCajaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.26.24.199;Initial Catalog=SistemaFacturacionMedico;User ID=sa" SettingsObjectName="DSSistemaPuntoVentaClinico.Data.Properties.Settings" SettingsPropertyName="SistemaFacturacionMedicoConnectionString4" Provider="System.Data.SqlClient" />
  <Function Name="Caja.SP_BUSCA_MONEDA" Method="SP_BUSCA_MONEDA">
    <Parameter Name="IdMoneda" Parameter="idMoneda" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoMoneda" Parameter="codigoMoneda" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_MONEDAResult">
      <Column Name="IdMoneda" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoMoneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Moneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sigla" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="PorDefault0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorDefecto" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_MANTENIMIENTO_MONEDAS" Method="SP_MANTENIMIENTO_MONEDAS">
    <Parameter Name="IdMoneda" Parameter="idMoneda" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoMoneda" Parameter="codigoMoneda" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Sigla" Parameter="sigla" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Tasa" Parameter="tasa" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PorDefault" Parameter="porDefault" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Idusuario" Parameter="idusuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_MONEDASResult">
      <Column Name="IdMoneda" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoMoneda" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sigla" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Tasa" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorDefault" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_BUSCA_CAJA" Method="SP_BUSCA_CAJA">
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoCaja" Parameter="codigoCaja" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_BUSCA_CAJAResult">
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoCaja" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoActual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_MANTENIMIENTO_CAJA" Method="SP_MANTENIMIENTO_CAJA">
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoCaja" Parameter="codigoCaja" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MontoActual" Parameter="montoActual" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CAJAResult">
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoCaja" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoActual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_MANTENIMIENTO_HISTORIAL_CAJA" Method="SP_MANTENIMIENTO_HISTORIAL_CAJA">
    <Parameter Name="IdistorialCaja" Parameter="idistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCaja" Parameter="idCaja" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroReferencia" Parameter="numeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_HISTORIAL_CAJAResult">
      <Column Name="IdistorialCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_MOSTRAR_HISTORIAL_CAJA" Method="SP_MOSTRAR_HISTORIAL_CAJA">
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_MOSTRAR_HISTORIAL_CAJAResult">
      <Column Name="IdistorialCaja" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdCaja" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CantidadFacturado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Anuladas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalCantidadFacturado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadCotizaciones" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadCirugiasProgramadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Caja" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Fecha0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Caja.SP_BUSCAR_PAGOS_FACTURAS" Method="SP_BUSCAR_PAGOS_FACTURAS">
    <Parameter Name="NumeroRecibo" Parameter="numeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaPagoDesde" Parameter="fechaPagoDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaPagoHasta" Parameter="fechaPagoHasta" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_BUSCAR_PAGOS_FACTURASResult">
      <Column Name="NumeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="PagandoA" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombrePaciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaPago" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MontoFactura" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Cobros.SP_APLICAR_PAGOS_FACTURAS" Method="SP_APLICAR_PAGOS_FACTURAS">
    <Parameter Name="NumeroRecibo" Parameter="numeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdPaciente" Parameter="idPaciente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Pendiente" Parameter="pendiente" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Cambio" Parameter="cambio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_APLICAR_PAGOS_FACTURASResult">
      <Column Name="NumeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdPaciente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Pendiente" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Cambio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaPago" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>