<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaFacturacionMedico" Class="BDContabilidadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=SistemaFacturacionMedico;User ID=sa" SettingsObjectName="DSSistemaPuntoVentaClinico.Data.Properties.Settings" SettingsPropertyName="SistemaFacturacionMedicoConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="Contabilidad.SP_GENERAR_COMPROBANTE_FISCAL" Method="SP_GENERAR_COMPROBANTE_FISCAL">
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_GENERAR_COMPROBANTE_FISCALResult">
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(8000) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_BUSCA_COMPROBANTES_FISCALES" Method="SP_BUSCA_COMPROBANTES_FISCALES">
    <Parameter Name="IdComprobanteFiscales" Parameter="idComprobanteFiscales" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_COMPROBANTES_FISCALESResult">
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Serie" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Secuencial" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SecuenciaInicial" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SecuenciaFinal" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Limite" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ValidoHasta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PorDefecto0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorDefecto" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Posiciones" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_MANTENIMIENTO_COMPROBANTE_FISCALES" Method="SP_MANTENIMIENTO_COMPROBANTE_FISCALES">
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Serie" Parameter="serie" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="TipoComprobante" Parameter="tipoComprobante" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="Secuencial" Parameter="secuencial" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="SecuenciaInicial" Parameter="secuenciaInicial" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="SecuenciaFinal" Parameter="secuenciaFinal" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Limite" Parameter="limite" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="ValidoHasta" Parameter="validoHasta" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PorDefecto" Parameter="porDefecto" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Posiciones" Parameter="posiciones" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult">
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Serie" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Secuencial" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SecuenciaInicial" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SecuenciaFinal" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Limite" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ValidoHasta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PorDefecto" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Posiciones" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_GUARDAR_CUENTA_POR_PAGAR" Method="SP_GUARDAR_CUENTA_POR_PAGAR">
    <Parameter Name="IdCuentaPorPagar" Parameter="idCuentaPorPagar" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdPaciente" Parameter="idPaciente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="BalanceInicial" Parameter="balanceInicial" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="BalanceActual" Parameter="balanceActual" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="CantidadPagos" Parameter="cantidadPagos" Type="System.Int32" DbType="Int" />
    <Parameter Name="Secuencia" Parameter="secuencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_CUENTA_POR_PAGARResult">
      <Column Name="IdCuentaPorPagar" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdPaciente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="BalanceInicial" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="BalanceActual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadPagos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_BUSCA_CUENTAS_POR_COBRAR" Method="SP_BUSCA_CUENTAS_POR_COBRAR">
    <Parameter Name="IdCuentaCobrar" Parameter="idCuentaCobrar" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdPaciente" Parameter="idPaciente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CUENTAS_POR_COBRARResult">
      <Column Name="IdCuentaPorPagar" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdPaciente" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Paciente" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Secuencia" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombrePaciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValidoHasta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BalanceInicial" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="BalanceActual" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.String" DbType="VarChar(38) NOT NULL" CanBeNull="false" />
      <Column Name="FechaVencimiento" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DiasAtrasados" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="DiasCredito" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Abono" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Pendiente" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="[0-30]" Member="_0_30" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[31-60]" Member="_31_60" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[61-90]" Member="_61_90" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[91-120]" Member="_91_120" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="[121 o Mas]" Member="_121_o_Mas" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_GUARDAR_COMISION_MEDICO" Method="SP_GUARDAR_COMISION_MEDICO">
    <Parameter Name="IDComision" Parameter="iDComision" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProgramacionCirugia" Parameter="idProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroReferencia" Parameter="numeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdAsistente" Parameter="idAsistente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCirugia" Parameter="fechaCirugia" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ComisionPagada" Parameter="comisionPagada" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="MontoPagado" Parameter="montoPagado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_COMISION_MEDICOResult">
      <Column Name="IDComision" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Idmedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdAsistente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCirugia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ComisionPagada" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FechapagoComision" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Contabilidad.SP_BUSCA_COMISIONES_MEDICOS" Method="SP_BUSCA_COMISIONES_MEDICOS">
    <Parameter Name="IDComision" Parameter="iDComision" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProgramacionCirugia" Parameter="idProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroReferencia" Parameter="numeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdAsistente" Parameter="idAsistente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCirugiaDesde" Parameter="fechaCirugiaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaCirugiaHasta" Parameter="fechaCirugiaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ComisionPagada" Parameter="comisionPagada" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_COMISIONES_MEDICOSResult">
      <Column Name="IDComision" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Cliente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Paciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CentroSalud" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Idmedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Medico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PorcComisionMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TipoVenta0" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoVenta" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="MontoFactura" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFacturaNeta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ComisionPagar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdAsistente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCirugia0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaCirugia" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ComisionPagada0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ComisionPagada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="FechapagoComision0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechapagoComision" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>