#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSSistemaPuntoVentaClinico.Data.Conexiones.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaFacturacionMedico")]
	public partial class BDContabilidadDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDContabilidadDataContext() : 
				base(global::DSSistemaPuntoVentaClinico.Data.Properties.Settings.Default.SistemaFacturacionMedicoConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public BDContabilidadDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDContabilidadDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDContabilidadDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDContabilidadDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Contabilidad.SP_GENERAR_COMPROBANTE_FISCAL")]
		public ISingleResult<SP_GENERAR_COMPROBANTE_FISCALResult> SP_GENERAR_COMPROBANTE_FISCAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobante", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobante)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idComprobante);
			return ((ISingleResult<SP_GENERAR_COMPROBANTE_FISCALResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Contabilidad.SP_BUSCA_COMPROBANTES_FISCALES")]
		public ISingleResult<SP_BUSCA_COMPROBANTES_FISCALESResult> SP_BUSCA_COMPROBANTES_FISCALES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobanteFiscales", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobanteFiscales)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idComprobanteFiscales);
			return ((ISingleResult<SP_BUSCA_COMPROBANTES_FISCALESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Contabilidad.SP_MANTENIMIENTO_COMPROBANTE_FISCALES")]
		public ISingleResult<SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult> SP_MANTENIMIENTO_COMPROBANTE_FISCALES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobante", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Serie", DbType="VarChar(1)")] string serie, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoComprobante", DbType="VarChar(2)")] string tipoComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Secuencial", DbType="BigInt")] System.Nullable<long> secuencial, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecuenciaInicial", DbType="BigInt")] System.Nullable<long> secuenciaInicial, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SecuenciaFinal", DbType="BigInt")] System.Nullable<long> secuenciaFinal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Limite", DbType="BigInt")] System.Nullable<long> limite, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ValidoHasta", DbType="VarChar(50)")] string validoHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PorDefecto", DbType="Bit")] System.Nullable<bool> porDefecto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Posiciones", DbType="BigInt")] System.Nullable<long> posiciones, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idComprobante, descripcion, serie, tipoComprobante, secuencial, secuenciaInicial, secuenciaFinal, limite, estatus, validoHasta, porDefecto, posiciones, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Contabilidad.SP_GUARDAR_CUENTA_POR_PAGAR")]
		public ISingleResult<SP_GUARDAR_CUENTA_POR_PAGARResult> SP_GUARDAR_CUENTA_POR_PAGAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCuentaPorPagar", DbType="Decimal(20,0)")] System.Nullable<decimal> idCuentaPorPagar, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPaciente", DbType="Decimal(20,0)")] System.Nullable<decimal> idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConector", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroConector, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BalanceInicial", DbType="Decimal(20,2)")] System.Nullable<decimal> balanceInicial, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BalanceActual", DbType="Decimal(20,2)")] System.Nullable<decimal> balanceActual, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadPagos", DbType="Int")] System.Nullable<int> cantidadPagos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Secuencia", DbType="Decimal(20,0)")] System.Nullable<decimal> secuencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCuentaPorPagar, idPaciente, numeroConector, balanceInicial, balanceActual, cantidadPagos, secuencia, accion);
			return ((ISingleResult<SP_GUARDAR_CUENTA_POR_PAGARResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Contabilidad.SP_BUSCA_CUENTAS_POR_COBRAR")]
		public ISingleResult<SP_BUSCA_CUENTAS_POR_COBRARResult> SP_BUSCA_CUENTAS_POR_COBRAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCuentaCobrar", DbType="Decimal(20,0)")] System.Nullable<decimal> idCuentaCobrar, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPaciente", DbType="VarChar(100)")] string idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNC", DbType="VarChar(100)")] string rNC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroConector", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroConector, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="VarChar(100)")] string numeroFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaDesde", DbType="Date")] System.Nullable<System.DateTime> fechaDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaHasta", DbType="Date")] System.Nullable<System.DateTime> fechaHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCuentaCobrar, idPaciente, rNC, numeroConector, numeroFactura, fechaDesde, fechaHasta, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_CUENTAS_POR_COBRARResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Contabilidad.SP_GUARDAR_COMISION_MEDICO")]
		public ISingleResult<SP_GUARDAR_COMISION_MEDICOResult> SP_GUARDAR_COMISION_MEDICO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDComision", DbType="Decimal(20,0)")] System.Nullable<decimal> iDComision, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProgramacionCirugia", DbType="Decimal(20,0)")] System.Nullable<decimal> idProgramacionCirugia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroReferencia", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroReferencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCentroSalud", DbType="Decimal(20,0)")] System.Nullable<decimal> idCentroSalud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedico", DbType="Decimal(20,0)")] System.Nullable<decimal> idMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAsistente", DbType="Decimal(20,0)")] System.Nullable<decimal> idAsistente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCirugia", DbType="Date")] System.Nullable<System.DateTime> fechaCirugia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ComisionPagada", DbType="Bit")] System.Nullable<bool> comisionPagada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoPagado", DbType="Decimal(20,2)")] System.Nullable<decimal> montoPagado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDComision, idProgramacionCirugia, numeroFactura, numeroReferencia, idCentroSalud, idMedico, idAsistente, fechaCirugia, comisionPagada, montoPagado, accion);
			return ((ISingleResult<SP_GUARDAR_COMISION_MEDICOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Contabilidad.SP_BUSCA_COMISIONES_MEDICOS")]
		public ISingleResult<SP_BUSCA_COMISIONES_MEDICOSResult> SP_BUSCA_COMISIONES_MEDICOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDComision", DbType="Decimal(20,0)")] System.Nullable<decimal> iDComision, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProgramacionCirugia", DbType="Decimal(20,0)")] System.Nullable<decimal> idProgramacionCirugia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroFactura", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroFactura, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroReferencia", DbType="Decimal(20,0)")] System.Nullable<decimal> numeroReferencia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCentroSalud", DbType="Decimal(20,0)")] System.Nullable<decimal> idCentroSalud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedico", DbType="Decimal(20,0)")] System.Nullable<decimal> idMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreMedico", DbType="VarChar(200)")] string nombreMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAsistente", DbType="Decimal(20,0)")] System.Nullable<decimal> idAsistente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCirugiaDesde", DbType="Date")] System.Nullable<System.DateTime> fechaCirugiaDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaCirugiaHasta", DbType="Date")] System.Nullable<System.DateTime> fechaCirugiaHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ComisionPagada", DbType="Bit")] System.Nullable<bool> comisionPagada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDComision, idProgramacionCirugia, numeroFactura, numeroReferencia, idCentroSalud, idMedico, nombreMedico, idAsistente, fechaCirugiaDesde, fechaCirugiaHasta, comisionPagada, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_COMISIONES_MEDICOSResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_GENERAR_COMPROBANTE_FISCALResult
	{
		
		private string _TipoComprobante;
		
		private string _Comprobante;
		
		public SP_GENERAR_COMPROBANTE_FISCALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoComprobante", DbType="VarChar(100)")]
		public string TipoComprobante
		{
			get
			{
				return this._TipoComprobante;
			}
			set
			{
				if ((this._TipoComprobante != value))
				{
					this._TipoComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comprobante", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string Comprobante
		{
			get
			{
				return this._Comprobante;
			}
			set
			{
				if ((this._Comprobante != value))
				{
					this._Comprobante = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_COMPROBANTES_FISCALESResult
	{
		
		private System.Nullable<decimal> _IdComprobante;
		
		private string _Comprobante;
		
		private string _Serie;
		
		private string _TipoComprobante;
		
		private System.Nullable<long> _Secuencial;
		
		private System.Nullable<long> _SecuenciaInicial;
		
		private System.Nullable<long> _SecuenciaFinal;
		
		private System.Nullable<long> _Limite;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private string _ValidoHasta;
		
		private System.Nullable<bool> _PorDefecto0;
		
		private string _PorDefecto;
		
		private System.Nullable<long> _Posiciones;
		
		public SP_BUSCA_COMPROBANTES_FISCALESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComprobante", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdComprobante
		{
			get
			{
				return this._IdComprobante;
			}
			set
			{
				if ((this._IdComprobante != value))
				{
					this._IdComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comprobante", DbType="VarChar(100)")]
		public string Comprobante
		{
			get
			{
				return this._Comprobante;
			}
			set
			{
				if ((this._Comprobante != value))
				{
					this._Comprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serie", DbType="VarChar(1)")]
		public string Serie
		{
			get
			{
				return this._Serie;
			}
			set
			{
				if ((this._Serie != value))
				{
					this._Serie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoComprobante", DbType="VarChar(2)")]
		public string TipoComprobante
		{
			get
			{
				return this._TipoComprobante;
			}
			set
			{
				if ((this._TipoComprobante != value))
				{
					this._TipoComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secuencial", DbType="BigInt")]
		public System.Nullable<long> Secuencial
		{
			get
			{
				return this._Secuencial;
			}
			set
			{
				if ((this._Secuencial != value))
				{
					this._Secuencial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecuenciaInicial", DbType="BigInt")]
		public System.Nullable<long> SecuenciaInicial
		{
			get
			{
				return this._SecuenciaInicial;
			}
			set
			{
				if ((this._SecuenciaInicial != value))
				{
					this._SecuenciaInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecuenciaFinal", DbType="BigInt")]
		public System.Nullable<long> SecuenciaFinal
		{
			get
			{
				return this._SecuenciaFinal;
			}
			set
			{
				if ((this._SecuenciaFinal != value))
				{
					this._SecuenciaFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Limite", DbType="BigInt")]
		public System.Nullable<long> Limite
		{
			get
			{
				return this._Limite;
			}
			set
			{
				if ((this._Limite != value))
				{
					this._Limite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8)")]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidoHasta", DbType="VarChar(50)")]
		public string ValidoHasta
		{
			get
			{
				return this._ValidoHasta;
			}
			set
			{
				if ((this._ValidoHasta != value))
				{
					this._ValidoHasta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorDefecto0", DbType="Bit")]
		public System.Nullable<bool> PorDefecto0
		{
			get
			{
				return this._PorDefecto0;
			}
			set
			{
				if ((this._PorDefecto0 != value))
				{
					this._PorDefecto0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorDefecto", DbType="VarChar(2)")]
		public string PorDefecto
		{
			get
			{
				return this._PorDefecto;
			}
			set
			{
				if ((this._PorDefecto != value))
				{
					this._PorDefecto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posiciones", DbType="BigInt")]
		public System.Nullable<long> Posiciones
		{
			get
			{
				return this._Posiciones;
			}
			set
			{
				if ((this._Posiciones != value))
				{
					this._Posiciones = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult
	{
		
		private System.Nullable<decimal> _IdComprobante;
		
		private string _Descripcion;
		
		private string _Serie;
		
		private string _TipoComprobante;
		
		private System.Nullable<long> _Secuencial;
		
		private System.Nullable<long> _SecuenciaInicial;
		
		private System.Nullable<long> _SecuenciaFinal;
		
		private System.Nullable<long> _Limite;
		
		private System.Nullable<bool> _Estatus;
		
		private string _ValidoHasta;
		
		private System.Nullable<bool> _PorDefecto;
		
		private System.Nullable<long> _Posiciones;
		
		public SP_MANTENIMIENTO_COMPROBANTE_FISCALESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComprobante", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdComprobante
		{
			get
			{
				return this._IdComprobante;
			}
			set
			{
				if ((this._IdComprobante != value))
				{
					this._IdComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Serie", DbType="VarChar(1)")]
		public string Serie
		{
			get
			{
				return this._Serie;
			}
			set
			{
				if ((this._Serie != value))
				{
					this._Serie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoComprobante", DbType="VarChar(2)")]
		public string TipoComprobante
		{
			get
			{
				return this._TipoComprobante;
			}
			set
			{
				if ((this._TipoComprobante != value))
				{
					this._TipoComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secuencial", DbType="BigInt")]
		public System.Nullable<long> Secuencial
		{
			get
			{
				return this._Secuencial;
			}
			set
			{
				if ((this._Secuencial != value))
				{
					this._Secuencial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecuenciaInicial", DbType="BigInt")]
		public System.Nullable<long> SecuenciaInicial
		{
			get
			{
				return this._SecuenciaInicial;
			}
			set
			{
				if ((this._SecuenciaInicial != value))
				{
					this._SecuenciaInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecuenciaFinal", DbType="BigInt")]
		public System.Nullable<long> SecuenciaFinal
		{
			get
			{
				return this._SecuenciaFinal;
			}
			set
			{
				if ((this._SecuenciaFinal != value))
				{
					this._SecuenciaFinal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Limite", DbType="BigInt")]
		public System.Nullable<long> Limite
		{
			get
			{
				return this._Limite;
			}
			set
			{
				if ((this._Limite != value))
				{
					this._Limite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidoHasta", DbType="VarChar(50)")]
		public string ValidoHasta
		{
			get
			{
				return this._ValidoHasta;
			}
			set
			{
				if ((this._ValidoHasta != value))
				{
					this._ValidoHasta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorDefecto", DbType="Bit")]
		public System.Nullable<bool> PorDefecto
		{
			get
			{
				return this._PorDefecto;
			}
			set
			{
				if ((this._PorDefecto != value))
				{
					this._PorDefecto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Posiciones", DbType="BigInt")]
		public System.Nullable<long> Posiciones
		{
			get
			{
				return this._Posiciones;
			}
			set
			{
				if ((this._Posiciones != value))
				{
					this._Posiciones = value;
				}
			}
		}
	}
	
	public partial class SP_GUARDAR_CUENTA_POR_PAGARResult
	{
		
		private System.Nullable<decimal> _IdCuentaPorPagar;
		
		private System.Nullable<decimal> _IdPaciente;
		
		private System.Nullable<decimal> _NumeroConector;
		
		private System.Nullable<decimal> _BalanceInicial;
		
		private System.Nullable<decimal> _BalanceActual;
		
		private System.Nullable<int> _CantidadPagos;
		
		public SP_GUARDAR_CUENTA_POR_PAGARResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCuentaPorPagar", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCuentaPorPagar
		{
			get
			{
				return this._IdCuentaPorPagar;
			}
			set
			{
				if ((this._IdCuentaPorPagar != value))
				{
					this._IdCuentaPorPagar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPaciente", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdPaciente
		{
			get
			{
				return this._IdPaciente;
			}
			set
			{
				if ((this._IdPaciente != value))
				{
					this._IdPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConector", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroConector
		{
			get
			{
				return this._NumeroConector;
			}
			set
			{
				if ((this._NumeroConector != value))
				{
					this._NumeroConector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceInicial", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> BalanceInicial
		{
			get
			{
				return this._BalanceInicial;
			}
			set
			{
				if ((this._BalanceInicial != value))
				{
					this._BalanceInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceActual", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> BalanceActual
		{
			get
			{
				return this._BalanceActual;
			}
			set
			{
				if ((this._BalanceActual != value))
				{
					this._BalanceActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadPagos", DbType="Int")]
		public System.Nullable<int> CantidadPagos
		{
			get
			{
				return this._CantidadPagos;
			}
			set
			{
				if ((this._CantidadPagos != value))
				{
					this._CantidadPagos = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_CUENTAS_POR_COBRARResult
	{
		
		private decimal _IdCuentaPorPagar;
		
		private decimal _IdPaciente;
		
		private string _Paciente;
		
		private string _TipoIdentificacion;
		
		private string _NoIdentificacion;
		
		private decimal _Secuencia;
		
		private System.Nullable<System.DateTime> _Fecha0;
		
		private System.Nullable<decimal> _NumeroConector;
		
		private string _NombrePaciente;
		
		private string _TipoComprobante;
		
		private string _ValidoHasta;
		
		private string _Comprobante;
		
		private System.Nullable<decimal> _BalanceInicial;
		
		private System.Nullable<decimal> _BalanceActual;
		
		private System.Nullable<decimal> _MontoPagado;
		
		private string _Concepto;
		
		private System.Nullable<decimal> _NumeroFactura;
		
		private string _FechaFacturacion;
		
		private string _FechaVencimiento;
		
		private System.Nullable<int> _DiasAtrasados;
		
		private string _Estatus;
		
		private System.Nullable<int> _DiasCredito;
		
		private System.Nullable<decimal> _Monto;
		
		private System.Nullable<decimal> _Abono;
		
		private System.Nullable<decimal> _Pendiente;
		
		private System.Nullable<decimal> @__0_30;
		
		private System.Nullable<decimal> @__31_60;
		
		private System.Nullable<decimal> @__61_90;
		
		private System.Nullable<decimal> @__91_120;
		
		private System.Nullable<decimal> @__121_o_Mas;
		
		public SP_BUSCA_CUENTAS_POR_COBRARResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCuentaPorPagar", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdCuentaPorPagar
		{
			get
			{
				return this._IdCuentaPorPagar;
			}
			set
			{
				if ((this._IdCuentaPorPagar != value))
				{
					this._IdCuentaPorPagar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPaciente", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdPaciente
		{
			get
			{
				return this._IdPaciente;
			}
			set
			{
				if ((this._IdPaciente != value))
				{
					this._IdPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente", DbType="VarChar(500)")]
		public string Paciente
		{
			get
			{
				return this._Paciente;
			}
			set
			{
				if ((this._Paciente != value))
				{
					this._Paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoIdentificacion", DbType="VarChar(100)")]
		public string TipoIdentificacion
		{
			get
			{
				return this._TipoIdentificacion;
			}
			set
			{
				if ((this._TipoIdentificacion != value))
				{
					this._TipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoIdentificacion", DbType="VarChar(100)")]
		public string NoIdentificacion
		{
			get
			{
				return this._NoIdentificacion;
			}
			set
			{
				if ((this._NoIdentificacion != value))
				{
					this._NoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secuencia", DbType="Decimal(20,0) NOT NULL")]
		public decimal Secuencia
		{
			get
			{
				return this._Secuencia;
			}
			set
			{
				if ((this._Secuencia != value))
				{
					this._Secuencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha0", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha0
		{
			get
			{
				return this._Fecha0;
			}
			set
			{
				if ((this._Fecha0 != value))
				{
					this._Fecha0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroConector", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroConector
		{
			get
			{
				return this._NumeroConector;
			}
			set
			{
				if ((this._NumeroConector != value))
				{
					this._NumeroConector = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombrePaciente", DbType="VarChar(100)")]
		public string NombrePaciente
		{
			get
			{
				return this._NombrePaciente;
			}
			set
			{
				if ((this._NombrePaciente != value))
				{
					this._NombrePaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoComprobante", DbType="VarChar(100)")]
		public string TipoComprobante
		{
			get
			{
				return this._TipoComprobante;
			}
			set
			{
				if ((this._TipoComprobante != value))
				{
					this._TipoComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidoHasta", DbType="VarChar(50)")]
		public string ValidoHasta
		{
			get
			{
				return this._ValidoHasta;
			}
			set
			{
				if ((this._ValidoHasta != value))
				{
					this._ValidoHasta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comprobante", DbType="VarChar(100)")]
		public string Comprobante
		{
			get
			{
				return this._Comprobante;
			}
			set
			{
				if ((this._Comprobante != value))
				{
					this._Comprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceInicial", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> BalanceInicial
		{
			get
			{
				return this._BalanceInicial;
			}
			set
			{
				if ((this._BalanceInicial != value))
				{
					this._BalanceInicial = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BalanceActual", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> BalanceActual
		{
			get
			{
				return this._BalanceActual;
			}
			set
			{
				if ((this._BalanceActual != value))
				{
					this._BalanceActual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPagado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoPagado
		{
			get
			{
				return this._MontoPagado;
			}
			set
			{
				if ((this._MontoPagado != value))
				{
					this._MontoPagado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Concepto", DbType="VarChar(1000)")]
		public string Concepto
		{
			get
			{
				return this._Concepto;
			}
			set
			{
				if ((this._Concepto != value))
				{
					this._Concepto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this._NumeroFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaFacturacion", DbType="VarChar(38) NOT NULL", CanBeNull=false)]
		public string FechaFacturacion
		{
			get
			{
				return this._FechaFacturacion;
			}
			set
			{
				if ((this._FechaFacturacion != value))
				{
					this._FechaFacturacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaVencimiento", DbType="NVarChar(30)")]
		public string FechaVencimiento
		{
			get
			{
				return this._FechaVencimiento;
			}
			set
			{
				if ((this._FechaVencimiento != value))
				{
					this._FechaVencimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiasAtrasados", DbType="Int")]
		public System.Nullable<int> DiasAtrasados
		{
			get
			{
				return this._DiasAtrasados;
			}
			set
			{
				if ((this._DiasAtrasados != value))
				{
					this._DiasAtrasados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiasCredito", DbType="Int")]
		public System.Nullable<int> DiasCredito
		{
			get
			{
				return this._DiasCredito;
			}
			set
			{
				if ((this._DiasCredito != value))
				{
					this._DiasCredito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abono", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Abono
		{
			get
			{
				return this._Abono;
			}
			set
			{
				if ((this._Abono != value))
				{
					this._Abono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pendiente", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Pendiente
		{
			get
			{
				return this._Pendiente;
			}
			set
			{
				if ((this._Pendiente != value))
				{
					this._Pendiente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[0-30]", Storage="__0_30", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _0_30
		{
			get
			{
				return this.@__0_30;
			}
			set
			{
				if ((this.@__0_30 != value))
				{
					this.@__0_30 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[31-60]", Storage="__31_60", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _31_60
		{
			get
			{
				return this.@__31_60;
			}
			set
			{
				if ((this.@__31_60 != value))
				{
					this.@__31_60 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[61-90]", Storage="__61_90", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _61_90
		{
			get
			{
				return this.@__61_90;
			}
			set
			{
				if ((this.@__61_90 != value))
				{
					this.@__61_90 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[91-120]", Storage="__91_120", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _91_120
		{
			get
			{
				return this.@__91_120;
			}
			set
			{
				if ((this.@__91_120 != value))
				{
					this.@__91_120 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[121 o Mas]", Storage="__121_o_Mas", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> _121_o_Mas
		{
			get
			{
				return this.@__121_o_Mas;
			}
			set
			{
				if ((this.@__121_o_Mas != value))
				{
					this.@__121_o_Mas = value;
				}
			}
		}
	}
	
	public partial class SP_GUARDAR_COMISION_MEDICOResult
	{
		
		private System.Nullable<decimal> _IDComision;
		
		private System.Nullable<decimal> _IdProgramacionCirugia;
		
		private System.Nullable<decimal> _NumeroFactura;
		
		private System.Nullable<decimal> _NumeroReferencia;
		
		private System.Nullable<decimal> _IdCentroSalud;
		
		private System.Nullable<decimal> _Idmedico;
		
		private System.Nullable<decimal> _IdAsistente;
		
		private System.Nullable<System.DateTime> _FechaCirugia;
		
		private System.Nullable<bool> _ComisionPagada;
		
		private System.Nullable<System.DateTime> _FechapagoComision;
		
		private System.Nullable<decimal> _MontoPagado;
		
		public SP_GUARDAR_COMISION_MEDICOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDComision", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IDComision
		{
			get
			{
				return this._IDComision;
			}
			set
			{
				if ((this._IDComision != value))
				{
					this._IDComision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProgramacionCirugia", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdProgramacionCirugia
		{
			get
			{
				return this._IdProgramacionCirugia;
			}
			set
			{
				if ((this._IdProgramacionCirugia != value))
				{
					this._IdProgramacionCirugia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this._NumeroFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroReferencia", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> NumeroReferencia
		{
			get
			{
				return this._NumeroReferencia;
			}
			set
			{
				if ((this._NumeroReferencia != value))
				{
					this._NumeroReferencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCentroSalud", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCentroSalud
		{
			get
			{
				return this._IdCentroSalud;
			}
			set
			{
				if ((this._IdCentroSalud != value))
				{
					this._IdCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idmedico", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Idmedico
		{
			get
			{
				return this._Idmedico;
			}
			set
			{
				if ((this._Idmedico != value))
				{
					this._Idmedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistente", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdAsistente
		{
			get
			{
				return this._IdAsistente;
			}
			set
			{
				if ((this._IdAsistente != value))
				{
					this._IdAsistente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCirugia", DbType="Date")]
		public System.Nullable<System.DateTime> FechaCirugia
		{
			get
			{
				return this._FechaCirugia;
			}
			set
			{
				if ((this._FechaCirugia != value))
				{
					this._FechaCirugia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComisionPagada", DbType="Bit")]
		public System.Nullable<bool> ComisionPagada
		{
			get
			{
				return this._ComisionPagada;
			}
			set
			{
				if ((this._ComisionPagada != value))
				{
					this._ComisionPagada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechapagoComision", DbType="Date")]
		public System.Nullable<System.DateTime> FechapagoComision
		{
			get
			{
				return this._FechapagoComision;
			}
			set
			{
				if ((this._FechapagoComision != value))
				{
					this._FechapagoComision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPagado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoPagado
		{
			get
			{
				return this._MontoPagado;
			}
			set
			{
				if ((this._MontoPagado != value))
				{
					this._MontoPagado = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_COMISIONES_MEDICOSResult
	{
		
		private decimal _IDComision;
		
		private decimal _IdProgramacionCirugia;
		
		private decimal _NumeroFactura;
		
		private string _Cliente;
		
		private string _Paciente;
		
		private decimal _NumeroReferencia;
		
		private System.Nullable<decimal> _IdCentroSalud;
		
		private string _CentroSalud;
		
		private string _Telefonos;
		
		private string _Direccion;
		
		private System.Nullable<decimal> _Idmedico;
		
		private string _Medico;
		
		private System.Nullable<decimal> _PorcComisionMedico;
		
		private System.Nullable<decimal> _Impuesto;
		
		private System.Nullable<decimal> _TipoVenta0;
		
		private string _TipoVenta;
		
		private System.Nullable<decimal> _MontoFactura;
		
		private System.Nullable<decimal> _MontoFacturaNeta;
		
		private System.Nullable<decimal> _ComisionPagar;
		
		private System.Nullable<decimal> _IdAsistente;
		
		private System.Nullable<System.DateTime> _FechaCirugia0;
		
		private string _FechaCirugia;
		
		private string _Hora;
		
		private System.Nullable<bool> _ComisionPagada0;
		
		private string _ComisionPagada;
		
		private System.Nullable<System.DateTime> _FechapagoComision0;
		
		private string _FechapagoComision;
		
		private System.Nullable<decimal> _MontoPagado;
		
		public SP_BUSCA_COMISIONES_MEDICOSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDComision", DbType="Decimal(20,0) NOT NULL")]
		public decimal IDComision
		{
			get
			{
				return this._IDComision;
			}
			set
			{
				if ((this._IDComision != value))
				{
					this._IDComision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProgramacionCirugia", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdProgramacionCirugia
		{
			get
			{
				return this._IdProgramacionCirugia;
			}
			set
			{
				if ((this._IdProgramacionCirugia != value))
				{
					this._IdProgramacionCirugia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroFactura", DbType="Decimal(20,0) NOT NULL")]
		public decimal NumeroFactura
		{
			get
			{
				return this._NumeroFactura;
			}
			set
			{
				if ((this._NumeroFactura != value))
				{
					this._NumeroFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="VarChar(100)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this._Cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paciente", DbType="VarChar(100)")]
		public string Paciente
		{
			get
			{
				return this._Paciente;
			}
			set
			{
				if ((this._Paciente != value))
				{
					this._Paciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroReferencia", DbType="Decimal(20,0) NOT NULL")]
		public decimal NumeroReferencia
		{
			get
			{
				return this._NumeroReferencia;
			}
			set
			{
				if ((this._NumeroReferencia != value))
				{
					this._NumeroReferencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCentroSalud", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCentroSalud
		{
			get
			{
				return this._IdCentroSalud;
			}
			set
			{
				if ((this._IdCentroSalud != value))
				{
					this._IdCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroSalud", DbType="VarChar(200)")]
		public string CentroSalud
		{
			get
			{
				return this._CentroSalud;
			}
			set
			{
				if ((this._CentroSalud != value))
				{
					this._CentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonos", DbType="VarChar(100)")]
		public string Telefonos
		{
			get
			{
				return this._Telefonos;
			}
			set
			{
				if ((this._Telefonos != value))
				{
					this._Telefonos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idmedico", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> Idmedico
		{
			get
			{
				return this._Idmedico;
			}
			set
			{
				if ((this._Idmedico != value))
				{
					this._Idmedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Medico", DbType="VarChar(100)")]
		public string Medico
		{
			get
			{
				return this._Medico;
			}
			set
			{
				if ((this._Medico != value))
				{
					this._Medico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcComisionMedico", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> PorcComisionMedico
		{
			get
			{
				return this._PorcComisionMedico;
			}
			set
			{
				if ((this._PorcComisionMedico != value))
				{
					this._PorcComisionMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Impuesto", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				if ((this._Impuesto != value))
				{
					this._Impuesto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVenta0", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> TipoVenta0
		{
			get
			{
				return this._TipoVenta0;
			}
			set
			{
				if ((this._TipoVenta0 != value))
				{
					this._TipoVenta0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoVenta", DbType="VarChar(20)")]
		public string TipoVenta
		{
			get
			{
				return this._TipoVenta;
			}
			set
			{
				if ((this._TipoVenta != value))
				{
					this._TipoVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoFactura", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoFactura
		{
			get
			{
				return this._MontoFactura;
			}
			set
			{
				if ((this._MontoFactura != value))
				{
					this._MontoFactura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoFacturaNeta", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoFacturaNeta
		{
			get
			{
				return this._MontoFacturaNeta;
			}
			set
			{
				if ((this._MontoFacturaNeta != value))
				{
					this._MontoFacturaNeta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComisionPagar", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> ComisionPagar
		{
			get
			{
				return this._ComisionPagar;
			}
			set
			{
				if ((this._ComisionPagar != value))
				{
					this._ComisionPagar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistente", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdAsistente
		{
			get
			{
				return this._IdAsistente;
			}
			set
			{
				if ((this._IdAsistente != value))
				{
					this._IdAsistente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCirugia0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaCirugia0
		{
			get
			{
				return this._FechaCirugia0;
			}
			set
			{
				if ((this._FechaCirugia0 != value))
				{
					this._FechaCirugia0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCirugia", DbType="NVarChar(4000)")]
		public string FechaCirugia
		{
			get
			{
				return this._FechaCirugia;
			}
			set
			{
				if ((this._FechaCirugia != value))
				{
					this._FechaCirugia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hora", DbType="VarChar(20)")]
		public string Hora
		{
			get
			{
				return this._Hora;
			}
			set
			{
				if ((this._Hora != value))
				{
					this._Hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComisionPagada0", DbType="Bit")]
		public System.Nullable<bool> ComisionPagada0
		{
			get
			{
				return this._ComisionPagada0;
			}
			set
			{
				if ((this._ComisionPagada0 != value))
				{
					this._ComisionPagada0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ComisionPagada", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string ComisionPagada
		{
			get
			{
				return this._ComisionPagada;
			}
			set
			{
				if ((this._ComisionPagada != value))
				{
					this._ComisionPagada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechapagoComision0", DbType="Date")]
		public System.Nullable<System.DateTime> FechapagoComision0
		{
			get
			{
				return this._FechapagoComision0;
			}
			set
			{
				if ((this._FechapagoComision0 != value))
				{
					this._FechapagoComision0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechapagoComision", DbType="NVarChar(4000)")]
		public string FechapagoComision
		{
			get
			{
				return this._FechapagoComision;
			}
			set
			{
				if ((this._FechapagoComision != value))
				{
					this._FechapagoComision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoPagado", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoPagado
		{
			get
			{
				return this._MontoPagado;
			}
			set
			{
				if ((this._MontoPagado != value))
				{
					this._MontoPagado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
