#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSSistemaPuntoVentaClinico.Data.Conexiones.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaFacturacionMedico")]
	public partial class BDContabilidadDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDContabilidadDataContext() : 
				base(global::DSSistemaPuntoVentaClinico.Data.Properties.Settings.Default.SistemaFacturacionMedicoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDContabilidadDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDContabilidadDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDContabilidadDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDContabilidadDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Contabilidad.SP_GENERAR_COMPROBANTE_FISCAL")]
		public ISingleResult<SP_GENERAR_COMPROBANTE_FISCALResult> SP_GENERAR_COMPROBANTE_FISCAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobante", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobante)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idComprobante);
			return ((ISingleResult<SP_GENERAR_COMPROBANTE_FISCALResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_GENERAR_COMPROBANTE_FISCALResult
	{
		
		private string _TipoComprobante;
		
		private string _Comprobante;
		
		public SP_GENERAR_COMPROBANTE_FISCALResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoComprobante", DbType="VarChar(100)")]
		public string TipoComprobante
		{
			get
			{
				return this._TipoComprobante;
			}
			set
			{
				if ((this._TipoComprobante != value))
				{
					this._TipoComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comprobante", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string Comprobante
		{
			get
			{
				return this._Comprobante;
			}
			set
			{
				if ((this._Comprobante != value))
				{
					this._Comprobante = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
