<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaFacturacionMedico" Class="BDEmpresaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=SistemaFacturacionMedico;User ID=sa" SettingsObjectName="DSSistemaPuntoVentaClinico.Data.Properties.Settings" SettingsPropertyName="SistemaFacturacionMedicoConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="Empresa.SP_MANTENIMIENTO_CENTRO_SALUD" Method="SP_MANTENIMIENTO_CENTRO_SALUD">
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoCentroSalud" Parameter="codigoCentroSalud" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Telefonos" Parameter="telefonos" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CENTRO_SALUDResult">
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoCentroSalud" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_CENTRO_SALUD" Method="SP_BUSCA_CENTRO_SALUD">
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoCentroSalud" Parameter="codigoCentroSalud" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPAGINA" Parameter="numeroPAGINA" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumerosRegistros" Parameter="numerosRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CENTRO_SALUDResult">
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoCentroSalud" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_SALAS" Method="SP_MANTENIMIENTO_SALAS">
    <Parameter Name="IdSala" Parameter="idSala" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoSala" Parameter="codigoSala" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_SALASResult">
      <Column Name="IdSala" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoSala" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_SALAS" Method="SP_BUSCA_SALAS">
    <Parameter Name="IdSala" Parameter="idSala" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoSala" Parameter="codigoSala" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_SALASResult">
      <Column Name="IdSala" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoSala" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_PACIENTES" Method="SP_MANTENIMIENTO_PACIENTES">
    <Parameter Name="IdPaciente" Parameter="idPaciente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoPaciente" Parameter="codigoPaciente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Sala" Parameter="sala" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoIdentificacion" Parameter="tipoIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdSexo" Parameter="idSexo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_PACIENTESResult">
      <Column Name="IdPaciente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoPaciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdSexo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_MEDICO" Method="SP_BUSCA_MEDICO">
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoMedico" Parameter="codigoMedico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NombreMedico" Parameter="nombreMedico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_MEDICOResult">
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoMedico" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NombreMedico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CentroSalud" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="fechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_MEDICO" Method="SP_MANTENIMIENTO_MEDICO">
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoMedico" Parameter="codigoMedico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NombreMedico" Parameter="nombreMedico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_MEDICOResult">
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoMedico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NombreMedico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_ARS" Method="SP_BUSCA_ARS">
    <Parameter Name="IdARS" Parameter="idARS" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoARS" Parameter="codigoARS" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPaina" Parameter="numeroPaina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_ARSResult">
      <Column Name="IdArs" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoARS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ARS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Representante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_ARS" Method="SP_MANTENIMIENTO_ARS">
    <Parameter Name="IdArs" Parameter="idArs" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoARS" Parameter="codigoARS" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Representante" Parameter="representante" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RNC" Parameter="rNC" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_ARSResult">
      <Column Name="IdArs" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoARS" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Representante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="RNC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_PACIENTES" Method="SP_BUSCA_PACIENTES">
    <Parameter Name="IdPaciente" Parameter="idPaciente" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoPaciente" Parameter="codigoPaciente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdComprobante" Parameter="idComprobante" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoIdentificacion" Parameter="tipoIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_PACIENTESResult">
      <Column Name="IdPaciente" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoPaciente" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IdComprobante" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CentroSalud" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Medico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificaion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdSexo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_BUSCA_ASISTENTE_CIRUGIA" Method="SP_BUSCA_ASISTENTE_CIRUGIA">
    <Parameter Name="IdAsistenteCirugia" Parameter="idAsistenteCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoAsistenteCirugia" Parameter="codigoAsistenteCirugia" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPaina" Parameter="numeroPaina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_ASISTENTE_CIRUGIAResult">
      <Column Name="IdAsistenteCirugia" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoAsistenteCirugia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="VarChar(38) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="VarChar(38) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="Empresa.SP_MANTENIMIENTO_ASISTENTE_CIRUGIA" Method="SP_MANTENIMIENTO_ASISTENTE_CIRUGIA">
    <Parameter Name="IdAsistenteCirugia" Parameter="idAsistenteCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoAsistenteCirugia" Parameter="codigoAsistenteCirugia" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoIdentificacion" Parameter="tipoIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_ASISTENTE_CIRUGIAResult">
      <Column Name="IdAsistenteCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoAsistenteCirugia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>