#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSSistemaPuntoVentaClinico.Data.Conexiones.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaFacturacionMedico")]
	public partial class BDEmpresaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDEmpresaDataContext() : 
				base(global::DSSistemaPuntoVentaClinico.Data.Properties.Settings.Default.SistemaFacturacionMedicoConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public BDEmpresaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDEmpresaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDEmpresaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDEmpresaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_CENTRO_SALUD")]
		public ISingleResult<SP_MANTENIMIENTO_CENTRO_SALUDResult> SP_MANTENIMIENTO_CENTRO_SALUD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCentroSalud", DbType="Decimal(18,0)")] System.Nullable<decimal> idCentroSalud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoCentroSalud", DbType="VarChar(100)")] string codigoCentroSalud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(8000)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefonos", DbType="VarChar(100)")] string telefonos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCentroSalud, codigoCentroSalud, nombre, direccion, telefonos, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_CENTRO_SALUDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_CENTRO_SALUD")]
		public ISingleResult<SP_BUSCA_CENTRO_SALUDResult> SP_BUSCA_CENTRO_SALUD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCentroSalud", DbType="Decimal(18,0)")] System.Nullable<decimal> idCentroSalud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoCentroSalud", DbType="VarChar(100)")] string codigoCentroSalud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPAGINA", DbType="Int")] System.Nullable<int> numeroPAGINA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumerosRegistros", DbType="Int")] System.Nullable<int> numerosRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCentroSalud, codigoCentroSalud, nombre, numeroPAGINA, numerosRegistros);
			return ((ISingleResult<SP_BUSCA_CENTRO_SALUDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_SALAS")]
		public ISingleResult<SP_MANTENIMIENTO_SALASResult> SP_MANTENIMIENTO_SALAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSala", DbType="Decimal(18,0)")] System.Nullable<decimal> idSala, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoSala", DbType="VarChar(100)")] string codigoSala, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSala, codigoSala, descripcion, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_SALASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_SALAS")]
		public ISingleResult<SP_BUSCA_SALASResult> SP_BUSCA_SALAS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSala", DbType="Decimal(18,0)")] System.Nullable<decimal> idSala, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoSala", DbType="VarChar(100)")] string codigoSala, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSala, codigoSala, descripcion, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_SALASResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_MEDICO")]
		public ISingleResult<SP_BUSCA_MEDICOResult> SP_BUSCA_MEDICO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedico", DbType="Decimal(18,0)")] System.Nullable<decimal> idMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoMedico", DbType="VarChar(100)")] string codigoMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreMedico", DbType="VarChar(100)")] string nombreMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCentroSalud", DbType="Decimal(18,0)")] System.Nullable<decimal> idCentroSalud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMedico, codigoMedico, nombreMedico, idCentroSalud, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_MEDICOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_MEDICO")]
		public ISingleResult<SP_MANTENIMIENTO_MEDICOResult> SP_MANTENIMIENTO_MEDICO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedico", DbType="Decimal(18,0)")] System.Nullable<decimal> idMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoMedico", DbType="VarChar(100)")] string codigoMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreMedico", DbType="VarChar(100)")] string nombreMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCentroSalud", DbType="Decimal(18,0)")] System.Nullable<decimal> idCentroSalud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMedico, codigoMedico, nombreMedico, idCentroSalud, email, estatus, idUsuario, telefono, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_MEDICOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_ARS")]
		public ISingleResult<SP_BUSCA_ARSResult> SP_BUSCA_ARS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdARS", DbType="Decimal(18,0)")] System.Nullable<decimal> idARS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoARS", DbType="VarChar(100)")] string codigoARS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPaina", DbType="Int")] System.Nullable<int> numeroPaina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idARS, codigoARS, descripcion, numeroPaina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_ARSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_ARS")]
		public ISingleResult<SP_MANTENIMIENTO_ARSResult> SP_MANTENIMIENTO_ARS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdArs", DbType="Decimal(18,0)")] System.Nullable<decimal> idArs, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoARS", DbType="VarChar(100)")] string codigoARS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Representante", DbType="VarChar(100)")] string representante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RNC", DbType="VarChar(50)")] string rNC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(20)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Correo", DbType="VarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(8000)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idArs, codigoARS, descripcion, estatus, idUsuario, representante, rNC, telefono, correo, direccion, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_ARSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_ASISTENTE_CIRUGIA")]
		public ISingleResult<SP_BUSCA_ASISTENTE_CIRUGIAResult> SP_BUSCA_ASISTENTE_CIRUGIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAsistenteCirugia", DbType="Decimal(20,0)")] System.Nullable<decimal> idAsistenteCirugia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoAsistenteCirugia", DbType="VarChar(100)")] string codigoAsistenteCirugia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPaina", DbType="Int")] System.Nullable<int> numeroPaina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAsistenteCirugia, codigoAsistenteCirugia, nombre, numeroPaina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_ASISTENTE_CIRUGIAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_ASISTENTE_CIRUGIA")]
		public ISingleResult<SP_MANTENIMIENTO_ASISTENTE_CIRUGIAResult> SP_MANTENIMIENTO_ASISTENTE_CIRUGIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAsistenteCirugia", DbType="Decimal(20,0)")] System.Nullable<decimal> idAsistenteCirugia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoAsistenteCirugia", DbType="VarChar(100)")] string codigoAsistenteCirugia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoIdentificacion", DbType="VarChar(100)")] string tipoIdentificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroIdentificacion", DbType="VarChar(100)")] string numeroIdentificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(100)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(8000)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAsistenteCirugia, codigoAsistenteCirugia, nombre, tipoIdentificacion, numeroIdentificacion, telefono, direccion, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_ASISTENTE_CIRUGIAResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MANTENIMIENTO_PACIENTES")]
		public ISingleResult<SP_MANTENIMIENTO_PACIENTESResult> SP_MANTENIMIENTO_PACIENTES(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPaciente", DbType="Decimal(20,0)")] System.Nullable<decimal> idPaciente, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoPaciente", DbType="VarChar(100)")] string codigoPaciente, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobante", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobante, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(50)")] string telefono, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCentroSalud", DbType="Decimal(20,0)")] System.Nullable<decimal> idCentroSalud, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sala", DbType="VarChar(100)")] string sala, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedico", DbType="Decimal(20,0)")] System.Nullable<decimal> idMedico, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoIdentificacion", DbType="Decimal(20,0)")] System.Nullable<decimal> idTipoIdentificacion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoIdentificacion", DbType="VarChar(100)")] string tipoIdentificacion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(8000)")] string direccion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSexo", DbType="Decimal(20,0)")] System.Nullable<decimal> idSexo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comentario", DbType="VarChar(8000)")] string comentario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(20,0)")] System.Nullable<decimal> idUsuario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoCredito", DbType="Decimal(20,2)")] System.Nullable<decimal> montoCredito, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPaciente, codigoPaciente, idComprobante, nombre, telefono, idCentroSalud, sala, idMedico, idTipoIdentificacion, tipoIdentificacion, direccion, idSexo, email, comentario, estatus, idUsuario, montoCredito, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_PACIENTESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_BUSCA_PACIENTES")]
		public ISingleResult<SP_BUSCA_PACIENTESResult> SP_BUSCA_PACIENTES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdPaciente", DbType="Decimal(20,0)")] System.Nullable<decimal> idPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoPaciente", DbType="VarChar(100)")] string codigoPaciente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdComprobante", DbType="Decimal(20,0)")] System.Nullable<decimal> idComprobante, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(500)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCentroSalud", DbType="Decimal(20,0)")] System.Nullable<decimal> idCentroSalud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMedico", DbType="Decimal(20,0)")] System.Nullable<decimal> idMedico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TipoIdentificacion", DbType="VarChar(100)")] string tipoIdentificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPaciente, codigoPaciente, idComprobante, nombre, idCentroSalud, idMedico, tipoIdentificacion, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_PACIENTESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_GENERAR_MONTO_CREDITO_GENERICO")]
		public ISingleResult<SP_GENERAR_MONTO_CREDITO_GENERICOResult> SP_GENERAR_MONTO_CREDITO_GENERICO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMontoCredito", DbType="Decimal(20,0)")] System.Nullable<decimal> idMontoCredito)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMontoCredito);
			return ((ISingleResult<SP_GENERAR_MONTO_CREDITO_GENERICOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Empresa.SP_MODIFICAR_MONTO_CREDITO_GENERICO")]
		public ISingleResult<SP_MODIFICAR_MONTO_CREDITO_GENERICOResult> SP_MODIFICAR_MONTO_CREDITO_GENERICO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdMontoCreditoGenerico", DbType="Decimal(20,0)")] System.Nullable<decimal> idMontoCreditoGenerico, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MontoCredito", DbType="Decimal(20,2)")] System.Nullable<decimal> montoCredito, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idMontoCreditoGenerico, montoCredito, accion);
			return ((ISingleResult<SP_MODIFICAR_MONTO_CREDITO_GENERICOResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_MANTENIMIENTO_CENTRO_SALUDResult
	{
		
		private System.Nullable<decimal> _IdCentroSalud;
		
		private string _CodigoCentroSalud;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefonos;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_CENTRO_SALUDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCentroSalud", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdCentroSalud
		{
			get
			{
				return this._IdCentroSalud;
			}
			set
			{
				if ((this._IdCentroSalud != value))
				{
					this._IdCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCentroSalud", DbType="VarChar(100)")]
		public string CodigoCentroSalud
		{
			get
			{
				return this._CodigoCentroSalud;
			}
			set
			{
				if ((this._CodigoCentroSalud != value))
				{
					this._CodigoCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonos", DbType="VarChar(100)")]
		public string Telefonos
		{
			get
			{
				return this._Telefonos;
			}
			set
			{
				if ((this._Telefonos != value))
				{
					this._Telefonos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_CENTRO_SALUDResult
	{
		
		private decimal _IdCentroSalud;
		
		private string _CodigoCentroSalud;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefonos;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_CENTRO_SALUDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCentroSalud", DbType="Decimal(18,0) NOT NULL")]
		public decimal IdCentroSalud
		{
			get
			{
				return this._IdCentroSalud;
			}
			set
			{
				if ((this._IdCentroSalud != value))
				{
					this._IdCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoCentroSalud", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CodigoCentroSalud
		{
			get
			{
				return this._CodigoCentroSalud;
			}
			set
			{
				if ((this._CodigoCentroSalud != value))
				{
					this._CodigoCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(200)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonos", DbType="VarChar(100)")]
		public string Telefonos
		{
			get
			{
				return this._Telefonos;
			}
			set
			{
				if ((this._Telefonos != value))
				{
					this._Telefonos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_SALASResult
	{
		
		private System.Nullable<decimal> _IdSala;
		
		private string _CodigoSala;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_SALASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSala", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdSala
		{
			get
			{
				return this._IdSala;
			}
			set
			{
				if ((this._IdSala != value))
				{
					this._IdSala = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoSala", DbType="VarChar(100)")]
		public string CodigoSala
		{
			get
			{
				return this._CodigoSala;
			}
			set
			{
				if ((this._CodigoSala != value))
				{
					this._CodigoSala = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_SALASResult
	{
		
		private System.Nullable<decimal> _IdSala;
		
		private string _CodigoSala;
		
		private string _Sala;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_SALASResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSala", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdSala
		{
			get
			{
				return this._IdSala;
			}
			set
			{
				if ((this._IdSala != value))
				{
					this._IdSala = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoSala", DbType="VarChar(100)")]
		public string CodigoSala
		{
			get
			{
				return this._CodigoSala;
			}
			set
			{
				if ((this._CodigoSala != value))
				{
					this._CodigoSala = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sala", DbType="VarChar(100)")]
		public string Sala
		{
			get
			{
				return this._Sala;
			}
			set
			{
				if ((this._Sala != value))
				{
					this._Sala = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_MEDICOResult
	{
		
		private decimal _IdMedico;
		
		private string _CodigoMedico;
		
		private string _NombreMedico;
		
		private string _Telefono;
		
		private System.Nullable<decimal> _IdCentroSalud;
		
		private string _CentroSalud;
		
		private string _Email;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _fechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_MEDICOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMedico", DbType="Decimal(18,0) NOT NULL")]
		public decimal IdMedico
		{
			get
			{
				return this._IdMedico;
			}
			set
			{
				if ((this._IdMedico != value))
				{
					this._IdMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMedico", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CodigoMedico
		{
			get
			{
				return this._CodigoMedico;
			}
			set
			{
				if ((this._CodigoMedico != value))
				{
					this._CodigoMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMedico", DbType="VarChar(100)")]
		public string NombreMedico
		{
			get
			{
				return this._NombreMedico;
			}
			set
			{
				if ((this._NombreMedico != value))
				{
					this._NombreMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCentroSalud", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdCentroSalud
		{
			get
			{
				return this._IdCentroSalud;
			}
			set
			{
				if ((this._IdCentroSalud != value))
				{
					this._IdCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroSalud", DbType="VarChar(200)")]
		public string CentroSalud
		{
			get
			{
				return this._CentroSalud;
			}
			set
			{
				if ((this._CentroSalud != value))
				{
					this._CentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> fechaModifica0
		{
			get
			{
				return this._fechaModifica0;
			}
			set
			{
				if ((this._fechaModifica0 != value))
				{
					this._fechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_MEDICOResult
	{
		
		private System.Nullable<decimal> _IdMedico;
		
		private string _CodigoMedico;
		
		private string _NombreMedico;
		
		private System.Nullable<decimal> _IdCentroSalud;
		
		private string _Email;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		private string _Telefono;
		
		public SP_MANTENIMIENTO_MEDICOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMedico", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdMedico
		{
			get
			{
				return this._IdMedico;
			}
			set
			{
				if ((this._IdMedico != value))
				{
					this._IdMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoMedico", DbType="VarChar(100)")]
		public string CodigoMedico
		{
			get
			{
				return this._CodigoMedico;
			}
			set
			{
				if ((this._CodigoMedico != value))
				{
					this._CodigoMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMedico", DbType="VarChar(100)")]
		public string NombreMedico
		{
			get
			{
				return this._NombreMedico;
			}
			set
			{
				if ((this._NombreMedico != value))
				{
					this._NombreMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCentroSalud", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdCentroSalud
		{
			get
			{
				return this._IdCentroSalud;
			}
			set
			{
				if ((this._IdCentroSalud != value))
				{
					this._IdCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_ARSResult
	{
		
		private System.Nullable<decimal> _IdArs;
		
		private string _CodigoARS;
		
		private string _ARS;
		
		private string _Representante;
		
		private string _RNC;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Direccion;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_ARSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArs", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdArs
		{
			get
			{
				return this._IdArs;
			}
			set
			{
				if ((this._IdArs != value))
				{
					this._IdArs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoARS", DbType="VarChar(100)")]
		public string CodigoARS
		{
			get
			{
				return this._CodigoARS;
			}
			set
			{
				if ((this._CodigoARS != value))
				{
					this._CodigoARS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARS", DbType="VarChar(100)")]
		public string ARS
		{
			get
			{
				return this._ARS;
			}
			set
			{
				if ((this._ARS != value))
				{
					this._ARS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Representante", DbType="VarChar(100)")]
		public string Representante
		{
			get
			{
				return this._Representante;
			}
			set
			{
				if ((this._Representante != value))
				{
					this._Representante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNC", DbType="VarChar(50)")]
		public string RNC
		{
			get
			{
				return this._RNC;
			}
			set
			{
				if ((this._RNC != value))
				{
					this._RNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_ARSResult
	{
		
		private System.Nullable<decimal> _IdArs;
		
		private string _CodigoARS;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		private string _Representante;
		
		private string _RNC;
		
		private string _Telefono;
		
		private string _Correo;
		
		private string _Direccion;
		
		public SP_MANTENIMIENTO_ARSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArs", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdArs
		{
			get
			{
				return this._IdArs;
			}
			set
			{
				if ((this._IdArs != value))
				{
					this._IdArs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoARS", DbType="VarChar(100)")]
		public string CodigoARS
		{
			get
			{
				return this._CodigoARS;
			}
			set
			{
				if ((this._CodigoARS != value))
				{
					this._CodigoARS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Representante", DbType="VarChar(100)")]
		public string Representante
		{
			get
			{
				return this._Representante;
			}
			set
			{
				if ((this._Representante != value))
				{
					this._Representante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNC", DbType="VarChar(50)")]
		public string RNC
		{
			get
			{
				return this._RNC;
			}
			set
			{
				if ((this._RNC != value))
				{
					this._RNC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(100)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_ASISTENTE_CIRUGIAResult
	{
		
		private decimal _IdAsistenteCirugia;
		
		private string _CodigoAsistenteCirugia;
		
		private string _Nombre;
		
		private string _TipoIdentificacion;
		
		private string _NumeroIdentificacion;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_ASISTENTE_CIRUGIAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistenteCirugia", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdAsistenteCirugia
		{
			get
			{
				return this._IdAsistenteCirugia;
			}
			set
			{
				if ((this._IdAsistenteCirugia != value))
				{
					this._IdAsistenteCirugia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoAsistenteCirugia", DbType="VarChar(100)")]
		public string CodigoAsistenteCirugia
		{
			get
			{
				return this._CodigoAsistenteCirugia;
			}
			set
			{
				if ((this._CodigoAsistenteCirugia != value))
				{
					this._CodigoAsistenteCirugia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoIdentificacion", DbType="VarChar(100)")]
		public string TipoIdentificacion
		{
			get
			{
				return this._TipoIdentificacion;
			}
			set
			{
				if ((this._TipoIdentificacion != value))
				{
					this._TipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroIdentificacion", DbType="VarChar(100)")]
		public string NumeroIdentificacion
		{
			get
			{
				return this._NumeroIdentificacion;
			}
			set
			{
				if ((this._NumeroIdentificacion != value))
				{
					this._NumeroIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(100)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="VarChar(38) NOT NULL", CanBeNull=false)]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="VarChar(38) NOT NULL", CanBeNull=false)]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_ASISTENTE_CIRUGIAResult
	{
		
		private System.Nullable<decimal> _IdAsistenteCirugia;
		
		private string _CodigoAsistenteCirugia;
		
		private string _Nombre;
		
		private string _TipoIdentificacion;
		
		private string _NumeroIdentificacion;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_ASISTENTE_CIRUGIAResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAsistenteCirugia", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdAsistenteCirugia
		{
			get
			{
				return this._IdAsistenteCirugia;
			}
			set
			{
				if ((this._IdAsistenteCirugia != value))
				{
					this._IdAsistenteCirugia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoAsistenteCirugia", DbType="VarChar(100)")]
		public string CodigoAsistenteCirugia
		{
			get
			{
				return this._CodigoAsistenteCirugia;
			}
			set
			{
				if ((this._CodigoAsistenteCirugia != value))
				{
					this._CodigoAsistenteCirugia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoIdentificacion", DbType="VarChar(100)")]
		public string TipoIdentificacion
		{
			get
			{
				return this._TipoIdentificacion;
			}
			set
			{
				if ((this._TipoIdentificacion != value))
				{
					this._TipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroIdentificacion", DbType="VarChar(100)")]
		public string NumeroIdentificacion
		{
			get
			{
				return this._NumeroIdentificacion;
			}
			set
			{
				if ((this._NumeroIdentificacion != value))
				{
					this._NumeroIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(100)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_PACIENTESResult
	{
		
		private System.Nullable<decimal> _IdPaciente;
		
		private string _CodigoPaciente;
		
		private System.Nullable<decimal> _IdComprobante;
		
		private string _Nombre;
		
		private string _Telefono;
		
		private System.Nullable<decimal> _IdCentroSalud;
		
		private string _Sala;
		
		private System.Nullable<decimal> _IdMedico;
		
		private System.Nullable<decimal> _IdTipoIdentificacion;
		
		private string _TipoIdentificacion;
		
		private string _Direccion;
		
		private System.Nullable<decimal> _IdSexo;
		
		private string _Email;
		
		private string _Comentario;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		private System.Nullable<decimal> _MontoCredito;
		
		public SP_MANTENIMIENTO_PACIENTESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPaciente", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdPaciente
		{
			get
			{
				return this._IdPaciente;
			}
			set
			{
				if ((this._IdPaciente != value))
				{
					this._IdPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPaciente", DbType="VarChar(100)")]
		public string CodigoPaciente
		{
			get
			{
				return this._CodigoPaciente;
			}
			set
			{
				if ((this._CodigoPaciente != value))
				{
					this._CodigoPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComprobante", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdComprobante
		{
			get
			{
				return this._IdComprobante;
			}
			set
			{
				if ((this._IdComprobante != value))
				{
					this._IdComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(500)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(100)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCentroSalud", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCentroSalud
		{
			get
			{
				return this._IdCentroSalud;
			}
			set
			{
				if ((this._IdCentroSalud != value))
				{
					this._IdCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sala", DbType="VarChar(100)")]
		public string Sala
		{
			get
			{
				return this._Sala;
			}
			set
			{
				if ((this._Sala != value))
				{
					this._Sala = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMedico", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMedico
		{
			get
			{
				return this._IdMedico;
			}
			set
			{
				if ((this._IdMedico != value))
				{
					this._IdMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoIdentificacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoIdentificacion
		{
			get
			{
				return this._IdTipoIdentificacion;
			}
			set
			{
				if ((this._IdTipoIdentificacion != value))
				{
					this._IdTipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoIdentificacion", DbType="VarChar(100)")]
		public string TipoIdentificacion
		{
			get
			{
				return this._TipoIdentificacion;
			}
			set
			{
				if ((this._TipoIdentificacion != value))
				{
					this._TipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSexo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdSexo
		{
			get
			{
				return this._IdSexo;
			}
			set
			{
				if ((this._IdSexo != value))
				{
					this._IdSexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(8000)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoCredito", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoCredito
		{
			get
			{
				return this._MontoCredito;
			}
			set
			{
				if ((this._MontoCredito != value))
				{
					this._MontoCredito = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_PACIENTESResult
	{
		
		private decimal _IdPaciente;
		
		private string _CodigoPaciente;
		
		private System.Nullable<decimal> _IdComprobante;
		
		private string _Comprobante;
		
		private string _Nombre;
		
		private string _Telefono;
		
		private System.Nullable<decimal> _MontoCredito;
		
		private System.Nullable<decimal> _IdCentroSalud;
		
		private string _CentroSalud;
		
		private string _Sala;
		
		private System.Nullable<decimal> _IdMedico;
		
		private string _Medico;
		
		private System.Nullable<decimal> _IdTipoIdentificacion;
		
		private string _TipoIdentificaion;
		
		private string _NumeroIdentificacion;
		
		private string _Direccion;
		
		private System.Nullable<decimal> _IdSexo;
		
		private string _Sexo;
		
		private string _Email;
		
		private string _Comentario;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_PACIENTESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPaciente", DbType="Decimal(20,0) NOT NULL")]
		public decimal IdPaciente
		{
			get
			{
				return this._IdPaciente;
			}
			set
			{
				if ((this._IdPaciente != value))
				{
					this._IdPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoPaciente", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CodigoPaciente
		{
			get
			{
				return this._CodigoPaciente;
			}
			set
			{
				if ((this._CodigoPaciente != value))
				{
					this._CodigoPaciente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdComprobante", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdComprobante
		{
			get
			{
				return this._IdComprobante;
			}
			set
			{
				if ((this._IdComprobante != value))
				{
					this._IdComprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comprobante", DbType="VarChar(100)")]
		public string Comprobante
		{
			get
			{
				return this._Comprobante;
			}
			set
			{
				if ((this._Comprobante != value))
				{
					this._Comprobante = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(500)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoCredito", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoCredito
		{
			get
			{
				return this._MontoCredito;
			}
			set
			{
				if ((this._MontoCredito != value))
				{
					this._MontoCredito = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCentroSalud", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdCentroSalud
		{
			get
			{
				return this._IdCentroSalud;
			}
			set
			{
				if ((this._IdCentroSalud != value))
				{
					this._IdCentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CentroSalud", DbType="VarChar(200)")]
		public string CentroSalud
		{
			get
			{
				return this._CentroSalud;
			}
			set
			{
				if ((this._CentroSalud != value))
				{
					this._CentroSalud = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sala", DbType="VarChar(100)")]
		public string Sala
		{
			get
			{
				return this._Sala;
			}
			set
			{
				if ((this._Sala != value))
				{
					this._Sala = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMedico", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMedico
		{
			get
			{
				return this._IdMedico;
			}
			set
			{
				if ((this._IdMedico != value))
				{
					this._IdMedico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Medico", DbType="VarChar(100)")]
		public string Medico
		{
			get
			{
				return this._Medico;
			}
			set
			{
				if ((this._Medico != value))
				{
					this._Medico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoIdentificacion", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdTipoIdentificacion
		{
			get
			{
				return this._IdTipoIdentificacion;
			}
			set
			{
				if ((this._IdTipoIdentificacion != value))
				{
					this._IdTipoIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoIdentificaion", DbType="VarChar(100)")]
		public string TipoIdentificaion
		{
			get
			{
				return this._TipoIdentificaion;
			}
			set
			{
				if ((this._TipoIdentificaion != value))
				{
					this._TipoIdentificaion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroIdentificacion", DbType="VarChar(100)")]
		public string NumeroIdentificacion
		{
			get
			{
				return this._NumeroIdentificacion;
			}
			set
			{
				if ((this._NumeroIdentificacion != value))
				{
					this._NumeroIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSexo", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdSexo
		{
			get
			{
				return this._IdSexo;
			}
			set
			{
				if ((this._IdSexo != value))
				{
					this._IdSexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="VarChar(100)")]
		public string Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this._Sexo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(8000)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this._Comentario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8)")]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_GENERAR_MONTO_CREDITO_GENERICOResult
	{
		
		private System.Nullable<decimal> _IdMontoCreditoGenerico;
		
		private System.Nullable<decimal> _MontoCredito;
		
		public SP_GENERAR_MONTO_CREDITO_GENERICOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMontoCreditoGenerico", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMontoCreditoGenerico
		{
			get
			{
				return this._IdMontoCreditoGenerico;
			}
			set
			{
				if ((this._IdMontoCreditoGenerico != value))
				{
					this._IdMontoCreditoGenerico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoCredito", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoCredito
		{
			get
			{
				return this._MontoCredito;
			}
			set
			{
				if ((this._MontoCredito != value))
				{
					this._MontoCredito = value;
				}
			}
		}
	}
	
	public partial class SP_MODIFICAR_MONTO_CREDITO_GENERICOResult
	{
		
		private System.Nullable<decimal> _IdMontoCreditoGenerico;
		
		private System.Nullable<decimal> _MontoCredito;
		
		public SP_MODIFICAR_MONTO_CREDITO_GENERICOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdMontoCreditoGenerico", DbType="Decimal(20,0)")]
		public System.Nullable<decimal> IdMontoCreditoGenerico
		{
			get
			{
				return this._IdMontoCreditoGenerico;
			}
			set
			{
				if ((this._IdMontoCreditoGenerico != value))
				{
					this._IdMontoCreditoGenerico = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoCredito", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> MontoCredito
		{
			get
			{
				return this._MontoCredito;
			}
			set
			{
				if ((this._MontoCredito != value))
				{
					this._MontoCredito = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
