<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaFacturacionMedico" Class="BDFacturacionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JUANMARCELINOMD;Initial Catalog=SistemaFacturacionMedico;User ID=sa" SettingsObjectName="DSSistemaPuntoVentaClinico.Data.Properties.Settings" SettingsPropertyName="SistemaFacturacionMedicoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="Facturacion.SP_BUSCA_TIPO_PAGO" Method="SP_BUSCA_TIPO_PAGO">
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoTipoPago" Parameter="codigoTipoPago" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_PAGOResult">
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoTipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="BloqueaMontoPagar0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BloqueaMontoPagar" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_MANTENIMIENTO_TIPO_PAGO" Method="SP_MANTENIMIENTO_TIPO_PAGO">
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoTipoPago" Parameter="codigoTipoPago" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="BloqueaMontoPagar" Parameter="bloqueaMontoPagar" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_TIPO_PAGOResult">
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoTipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BloqueaMontoPagar" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_GUARDAR_DATOS_FACTURACION_CLIENTE" Method="SP_GUARDAR_DATOS_FACTURACION_CLIENTE">
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEstatusFacturacion" Parameter="idEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoFacturacion" Parameter="codigoFacturacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoFacturacion" Parameter="idTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombrePaciente" Parameter="nombrePaciente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Sala" Parameter="sala" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdSexo" Parameter="idSexo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ComentarioPaciente" Parameter="comentarioPaciente" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="FechaFacturacion" Parameter="fechaFacturacion" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_DATOS_FACTURACION_CLIENTEResult">
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoFacturacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombrePaciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdSexo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ComentarioPaciente" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_SACAR_CALCULOS_FACTURACION" Method="SP_SACAR_CALCULOS_FACTURACION">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_SACAR_CALCULOS_FACTURACIONResult">
      <Column Name="CantidadArticulos" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="ToTalDescuento" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="PorcientoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_GUARDAR_FACTURACION_PRODUCTO" Method="SP_GUARDAR_FACTURACION_PRODUCTO">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="DescuentoAplicado" Parameter="descuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Secuencial" Parameter="secuencial" Type="System.Decimal" DbType="Decimal(38,0)" />
    <Parameter Name="NumeroPago" Parameter="numeroPago" Type="System.Decimal" DbType="Decimal(1,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_FACTURACION_PRODUCTOResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Secuencial" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="NumeroPago" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_BUSCA_PRODUCTOS_AGREGADOS_FACTURA" Method="SP_BUSCA_PRODUCTOS_AGREGADOS_FACTURA">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Secuencial" Parameter="secuencial" Type="System.Decimal" DbType="Decimal(38,0)" />
    <ElementType Name="SP_BUSCA_PRODUCTOS_AGREGADOS_FACTURAResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="LlevaDescuento0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LlevaDescuento" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PorcientoDescuento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Secuencial" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
      <Column Name="NumeroPago" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_GUARDAR_FACTURACION_COMPROBANTES" Method="SP_GUARDAR_FACTURACION_COMPROBANTES">
    <Parameter Name="IdFacturacion" Parameter="idFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoFacturacion" Parameter="codigoFacturacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoComprobante" Parameter="tipoComprobante" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Comprobante" Parameter="comprobante" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_FACTURACION_COMPROBANTESResult">
      <Column Name="IdFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoFacturacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_GUARDAR_DATOS_FACTURACION_CALCULOS" Method="SP_GUARDAR_DATOS_FACTURACION_CALCULOS">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CantidadArticulos" Parameter="cantidadArticulos" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TotalDescuento" Parameter="totalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Subtotal" Parameter="subtotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="MontoPagado" Parameter="montoPagado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdEstatusCirugia" Parameter="idEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_DATOS_FACTURACION_CALCULOSResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CantidadArticulos" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_MANTENIMIENTO_DATOS_FACTURACION_ESPEJO" Method="SP_MANTENIMIENTO_DATOS_FACTURACION_ESPEJO">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoFacturacion" Parameter="idTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombrePaciente" Parameter="nombrePaciente" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Sala" Parameter="sala" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdSexo" Parameter="idSexo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="GuardarCliente" Parameter="guardarCliente" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="TipoProceso" Parameter="tipoProceso" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEstatusirugia" Parameter="idEstatusirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_DATOS_FACTURACION_ESPEJOResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombrePaciente" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdSexo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="GuardarCliente" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TipoProceso" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdEstatusirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_BUSCA_DATOS_FACTURACION_ESPEJO" Method="SP_BUSCA_DATOS_FACTURACION_ESPEJO">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_DATOS_FACTURACION_ESPEJOResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoFacturacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NombrePaciente" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CentroSalud" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Medico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdSexo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="GuardarCliente" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TipoProceso" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdEstatusirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="EstatusCirugia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_MANTENIMIENTO_PROGRAMACION_CIRUGIA" Method="SP_MANTENIMIENTO_PROGRAMACION_CIRUGIA">
    <Parameter Name="IdProgramacionCirugia" Parameter="idProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaCirugia" Parameter="fechaCirugia" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEstatusCirugia" Parameter="idEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NoFactura" Parameter="noFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NoReferencia" Parameter="noReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(100)" />
    <ElementType Name="SP_MANTENIMIENTO_PROGRAMACION_CIRUGIAResult">
      <Column Name="IdProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaCirugia" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NoFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NoReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_BUSCA_FACTURACION_CALCULOS" Method="SP_BUSCA_FACTURACION_CALCULOS">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_BUSCA_FACTURACION_CALCULOSResult">
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CantidadArticulos" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Facturacion.SP_BUSCA_PROGRAMACION_CIRUGIA" Method="SP_BUSCA_PROGRAMACION_CIRUGIA">
    <Parameter Name="IdProgramacionCirugia" Parameter="idProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdEstatusCirugia" Parameter="idEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_PROGRAMACION_CIRUGIAResult">
      <Column Name="IdProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="FechaCirugia" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CentroSalud" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombreMedico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NoFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NoReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IdTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Paciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IdCentroSaludAnterior" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdMedicoAnterior" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdSexo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ComentarioPaciente" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="FechaFacturacion0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>