<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaFacturacionMedico" Class="BDHistorialDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JDIAZ0624;Initial Catalog=SistemaFacturacionMedico;User ID=sa" SettingsObjectName="DSSistemaPuntoVentaClinico.Data.Properties.Settings" SettingsPropertyName="SistemaFacturacionMedicoConnectionString2" Provider="System.Data.SqlClient" />
  <Function Name="Reporte.SP_SACAR_RUTA_REPORTE" Method="SP_SACAR_RUTA_REPORTE">
    <Parameter Name="IdReporte" Parameter="idReporte" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_SACAR_RUTA_REPORTEResult">
      <Column Name="IdReporte" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="DescripcionReporte" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="RutaReporte" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_MANTENIMIENTO_RUTA_REPORTES" Method="SP_MANTENIMIENTO_RUTA_REPORTES">
    <Parameter Name="IdReporte" Parameter="idReporte" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="DescripcionReporte" Parameter="descripcionReporte" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="RutaReporte" Parameter="rutaReporte" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_RUTA_REPORTESResult">
      <Column Name="IdReporte" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="DescripcionReporte" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="RutaReporte" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Historial.SP_MONTO_FACTURACION_COTIZACION" Method="SP_MONTO_FACTURACION_COTIZACION">
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_MONTO_FACTURACION_COTIZACIONResult">
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(38,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_MANTENIMIENTO_CUADRE_CAJA" Method="SP_MANTENIMIENTO_CUADRE_CAJA">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Caja" Parameter="caja" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CantidadFacturado" Parameter="cantidadFacturado" Type="System.Int32" DbType="Int" />
    <Parameter Name="Anuladas" Parameter="anuladas" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalCantidadFacturado" Parameter="totalCantidadFacturado" Type="System.Int32" DbType="Int" />
    <Parameter Name="CantidadCotizaciones" Parameter="cantidadCotizaciones" Type="System.Int32" DbType="Int" />
    <Parameter Name="CantidadCirugiasProgramadas" Parameter="cantidadCirugiasProgramadas" Type="System.Int32" DbType="Int" />
    <Parameter Name="Monto" Parameter="monto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Fecha" Parameter="fecha" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CreadoPor" Parameter="creadoPor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroReferencia" Parameter="numeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoPago" Parameter="tipoPago" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CUADRE_CAJAResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Caja" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadFacturado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Anuladas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalCantidadFacturado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadCotizaciones" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CantidadCirugiasProgramadas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Monto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaDesde" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaHasta" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_MANTENIMIENTO_REPORTE_PRODUCTO" Method="SP_MANTENIMIENTO_REPORTE_PRODUCTO">
    <Parameter Name="IdUsuarioImprime" Parameter="idUsuarioImprime" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoProducto" Parameter="codigoProducto" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Almacen" Parameter="almacen" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="TipoProveedor" Parameter="tipoProveedor" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Proveedor" Parameter="proveedor" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="TipoEmpaque" Parameter="tipoEmpaque" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="TipoProducto" Parameter="tipoProducto" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Producto" Parameter="producto" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(200)" />
    <Parameter Name="CantidadAlmacen" Parameter="cantidadAlmacen" Type="System.Int32" DbType="Int" />
    <Parameter Name="PrecioCompra" Parameter="precioCompra" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PrecioVenta" Parameter="precioVenta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="SegundoPrecio" Parameter="segundoPrecio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TercerPrecio" Parameter="tercerPrecio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="FechaEntrada" Parameter="fechaEntrada" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="LlevaDescuento" Parameter="llevaDescuento" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="PorcientoDescuento" Parameter="porcientoDescuento" Type="System.Int32" DbType="Int" />
    <Parameter Name="CreadoPor" Parameter="creadoPor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaAdiciona" Parameter="fechaAdiciona" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="ModificadoPor" Parameter="modificadoPor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaModifica" Parameter="fechaModifica" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_REPORTE_PRODUCTOResult">
      <Column Name="IdUsuarioImprime" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoProducto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Almacen" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoProveedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Proveedor" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoEmpaque" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CantidadAlmacen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="SegundoPrecio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TercerPrecio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaEntrada" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="LlevaDescuento" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="PorcientoDescuento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_MANTENIMIENTO_FACTURACION_CIRUGIA" Method="SP_MANTENIMIENTO_FACTURACION_CIRUGIA">
    <Parameter Name="IdUsuarioImprime" Parameter="idUsuarioImprime" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_FACTURACION_CIRUGIAResult">
      <Column Name="IdUsuarioImprime" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_MANTENIMIENTO_HISTORIAL_FACTURACION_COTIZACION" Method="SP_MANTENIMIENTO_HISTORIAL_FACTURACION_COTIZACION">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombrePaciente" Parameter="nombrePaciente" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="IdTipoIdentificacion" Parameter="idTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoIdentificacion" Parameter="tipoIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroIdentificacion" Parameter="numeroIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdEstatusFacturacion" Parameter="idEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CodigoFacturacion" Parameter="codigoFacturacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoFacturacion" Parameter="idTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoComprobante" Parameter="tipoComprobante" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ValidoHasta" Parameter="validoHasta" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Comprobante" Parameter="comprobante" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CentroSalud" Parameter="centroSalud" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Sala" Parameter="sala" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Medico" Parameter="medico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdSexo" Parameter="idSexo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Sexo" Parameter="sexo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ComentarioPaciente" Parameter="comentarioPaciente" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="FechaFacturacion0" Parameter="fechaFacturacion0" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFacturacion" Parameter="fechaFacturacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdUsuarioCrea" Parameter="idUsuarioCrea" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Creadopor" Parameter="creadopor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoProducto" Parameter="tipoProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ProDucto" Parameter="proDucto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="DescuentoAplicado" Parameter="descuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="CantidadArticulos" Parameter="cantidadArticulos" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TotalDescuento" Parameter="totalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Subtotal" Parameter="subtotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalGeneral" Parameter="totalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="TipoPago" Parameter="tipoPago" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MontoPagado" Parameter="montoPagado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_HISTORIAL_FACTURACION_COTIZACIONResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombrePaciente" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoFacturacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValidoHasta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CentroSalud" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Medico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdSexo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ComentarioPaciente" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="FechaFacturacion0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdUsuarioCrea" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Creadopor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ProDucto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadArticulos" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GUARDAR_HISTORIAL_PAGOS" Method="SP_GUARDAR_HISTORIAL_PAGOS">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroRecibo" Parameter="numeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaPago" Parameter="fechaPago" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MontoFactura" Parameter="montoFactura" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoPagado" Parameter="montoPagado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Concepto" Parameter="concepto" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="TipoPago" Parameter="tipoPago" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CreadoPor" Parameter="creadoPor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_HISTORIAL_PAGOSResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroRecibo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaPago" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MontoFactura" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Concepto" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Historial.SP_HISTORIAL_FACTURACION_COTIZACION" Method="SP_HISTORIAL_FACTURACION_COTIZACION">
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="NumeroConector" Parameter="numeroConector" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombrePaciente" Parameter="nombrePaciente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdEstatusFacturacion" Parameter="idEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoFacturacion" Parameter="codigoFacturacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoFacturacion" Parameter="idTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdCentroSalud" Parameter="idCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdMedico" Parameter="idMedico" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdTipoPago" Parameter="idTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="FechaFacturacionDesde" Parameter="fechaFacturacionDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaFacturacionHasta" Parameter="fechaFacturacionHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdEstatusCirugia" Parameter="idEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_HISTORIAL_FACTURACION_COTIZACIONResult">
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombrePaciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoIdentificacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CodigoFacturacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdTipoFacturacion" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ValidoHasta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Comprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="IdCentroSalud" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CentroSalud" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="IdMedico" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Medico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IdSexo" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ComentarioPaciente" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="FechaFacturacion0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="FechaVencimiento0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaVencimiento" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CantidadDias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiasDiferencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EstatusDias" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Creadopor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ProDucto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="CantidadArticulos" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdTipoPago" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="IdEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="EstatusCirugia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CirugiaProgramada0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CirugiaProgramada" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TipoVenta0" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoVenta01" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="TipoVenta" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="IdCantidadias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CodigoPaciente" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Paciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CedulaPaciente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Historial.SP_GUARDAR_REPORTE_VENTAS" Method="SP_GUARDAR_REPORTE_VENTAS">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NombrePaciente" Parameter="nombrePaciente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoIdentificacion" Parameter="tipoIdentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Numeroidentificacion" Parameter="numeroidentificacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoComprobante" Parameter="tipoComprobante" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CentroSalud" Parameter="centroSalud" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Sala" Parameter="sala" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Medico" Parameter="medico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Sexo" Parameter="sexo" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="ComentarioPaciente" Parameter="comentarioPaciente" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaFacturacion" Parameter="fechaFacturacion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaVencimiento" Parameter="fechaVencimiento" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CantidadDias" Parameter="cantidadDias" Type="System.Int32" DbType="Int" />
    <Parameter Name="DiasDiferencia" Parameter="diasDiferencia" Type="System.Int32" DbType="Int" />
    <Parameter Name="EstatusDias" Parameter="estatusDias" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CreadoPor" Parameter="creadoPor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoProducto" Parameter="tipoProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Producto" Parameter="producto" Type="System.String" DbType="VarChar(500)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="DescuentoAplicado" Parameter="descuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Total" Parameter="total" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalDescuento" Parameter="totalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="SubTotal" Parameter="subTotal" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Impuesto" Parameter="impuesto" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TotalGeneral" Parameter="totalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TipoPago" Parameter="tipoPago" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="MontoPagado" Parameter="montoPagado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="EstatusCirugia" Parameter="estatusCirugia" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="TipoVenta" Parameter="tipoVenta" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Balance" Parameter="balance" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_REPORTE_VENTASResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NombrePaciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoIdentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Numeroidentificacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoComprobante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CentroSalud" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Sala" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Medico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Sexo" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ComentarioPaciente" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FechaVencimiento" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CantidadDias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiasDiferencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EstatusDias" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="DescuentoAplicado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalDescuento" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="SubTotal" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="Impuesto" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TotalGeneral" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TipoPago" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="EstatusCirugia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TipoVenta" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Balance" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GUARDAR_REPORTE_COMISION_MEDICO_DETALLE" Method="SP_GUARDAR_REPORTE_COMISION_MEDICO_DETALLE">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IDComision" Parameter="iDComision" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProgramacionCirugia" Parameter="idProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroFactura" Parameter="numeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="NumeroReferencia" Parameter="numeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CentroSalud" Parameter="centroSalud" Type="System.String" DbType="VarChar(150)" />
    <Parameter Name="Medico" Parameter="medico" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="PorcComisionMedico" Parameter="porcComisionMedico" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoFactura" Parameter="montoFactura" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="MontoFacturaNeta" Parameter="montoFacturaNeta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="ComisionPagar" Parameter="comisionPagar" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="FechaCirugia" Parameter="fechaCirugia" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Hora" Parameter="hora" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ComisionPagada" Parameter="comisionPagada" Type="System.String" DbType="VarChar(2)" />
    <Parameter Name="FechaPagoComision" Parameter="fechaPagoComision" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="MontoPagado" Parameter="montoPagado" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_REPORTE_COMISION_MEDICO_DETALLEResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IDComision" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroReferencia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CentroSalud" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Medico" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="PorcComisionMedico" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFactura" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="MontoFacturaNeta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="ComisionPagar" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaCirugia" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Hora" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ComisionPagada" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="FechaPagoComision" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MontoPagado" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_SACAR_DATOS_FACTURACION_CIRUGIA" Method="SP_SACAR_DATOS_FACTURACION_CIRUGIA">
    <Parameter Name="FechaDesde" Parameter="fechaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaHasta" Parameter="fechaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="IdEstatusCirugia" Parameter="idEstatusCirugia" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SACAR_DATOS_FACTURACION_CIRUGIAResult">
      <Column Name="NumeroFactura" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="NumeroConector" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaFacturacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CirugiaProgramada" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdEstatusCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Estastus" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdEstatusFacturacion" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="EstatusCirugia" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Reporte.SP_GUARDAR_REPORTE_GASTOS_CIRUGIA" Method="SP_GUARDAR_REPORTE_GASTOS_CIRUGIA">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="IdProgramacionCirugia" Parameter="idProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Cantidad" Parameter="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Comentario" Parameter="comentario" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_GUARDAR_REPORTE_GASTOS_CIRUGIAResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="IdProgramacionCirugia" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>