#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSSistemaPuntoVentaClinico.Data.Conexiones.ConexionLINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SistemaFacturacionMedico")]
	public partial class BDInventarioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public BDInventarioDataContext() : 
				base(global::DSSistemaPuntoVentaClinico.Data.Properties.Settings.Default.SistemaFacturacionMedicoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDInventarioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDInventarioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDInventarioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDInventarioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_BUSCA_ALMACEN")]
		public ISingleResult<SP_BUSCA_ALMACENResult> SP_BUSCA_ALMACEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAlmacen", DbType="Decimal(18,0)")] System.Nullable<decimal> idAlmacen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoAlmacen", DbType="VarChar(100)")] string codigoAlmacen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAlmacen, codigoAlmacen, nombre, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_ALMACENResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_MANTENIMIENTO_ALMACEN")]
		public ISingleResult<SP_MANTENIMIENTO_ALMACENResult> SP_MANTENIMIENTO_ALMACEN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAlmacen", DbType="Decimal(18,0)")] System.Nullable<decimal> idAlmacen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoAlmacen", DbType="VarChar(100)")] string codigoAlmacen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(8000)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="VarChar(100)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idAlmacen, codigoAlmacen, nombre, direccion, telefono, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_ALMACENResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_BUSCA_TIPO_PROVEEDOR")]
		public ISingleResult<SP_BUSCA_TIPO_PROVEEDORResult> SP_BUSCA_TIPO_PROVEEDOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoTipoProveedor", DbType="VarChar(100)")] string codigoTipoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoProveedor, codigoTipoProveedor, descripcion, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_TIPO_PROVEEDORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_MANTENIMIENTO_PROVEEDOR")]
		public ISingleResult<SP_MANTENIMIENTO_PROVEEDORResult> SP_MANTENIMIENTO_PROVEEDOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoProveedor", DbType="VarChar(100)")] string codigoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(8000)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefonos", DbType="VarChar(100)")] string telefonos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fax", DbType="VarChar(20)")] string fax, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contacto", DbType="VarChar(70)")] string contacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LlevaComision", DbType="Bit")] System.Nullable<bool> llevaComision, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor, codigoProveedor, idTipoProveedor, nombre, direccion, telefonos, fax, contacto, llevaComision, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_PROVEEDORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_MANTENIMIENTO_TIPO_EMPAQUE")]
		public ISingleResult<SP_MANTENIMIENTO_TIPO_EMPAQUEResult> SP_MANTENIMIENTO_TIPO_EMPAQUE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoEmpaque", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoEmpaque, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoTipoEmpaque", DbType="VarChar(100)")] string codigoTipoEmpaque, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoEmpaque, codigoTipoEmpaque, descripcion, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_TIPO_EMPAQUEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_BUSCA_TIPO_EMPAQUE")]
		public ISingleResult<SP_BUSCA_TIPO_EMPAQUEResult> SP_BUSCA_TIPO_EMPAQUE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoEmpaque", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoEmpaque, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoTipoEmpaque", DbType="VarChar(100)")] string codigoTipoEmpaque, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoEmpaque, codigoTipoEmpaque, descripcion, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_TIPO_EMPAQUEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_BUSCA_TIPO_PRODUCTO")]
		public ISingleResult<SP_BUSCA_TIPO_PRODUCTOResult> SP_BUSCA_TIPO_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProducto", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoTipoProducto", DbType="VarChar(100)")] string codigoTipoProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoProducto, codigoTipoProducto, descripcion, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_TIPO_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_MANTENIMIENTO_TIPO_PRODUCTO")]
		public ISingleResult<SP_MANTENIMIENTO_TIPO_PRODUCTOResult> SP_MANTENIMIENTO_TIPO_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProducto", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoTipoProducto", DbType="VarChar(100)")] string codigoTipoProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoProducto, codigoTipoProducto, descripcion, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_TIPO_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_MANTENIMIENTO_TIPO_PROVEEDOR")]
		public ISingleResult<SP_MANTENIMIENTO_TIPO_PROVEEDORResult> SP_MANTENIMIENTO_TIPO_PROVEEDOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoTipoProveedor", DbType="VarChar(100)")] string codigoTipoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTipoProveedor, codigoTipoProveedor, descripcion, estatus, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_TIPO_PROVEEDORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_BUSCA_PROVEEDOR")]
		public ISingleResult<SP_BUSCA_PROVEEDORResult> SP_BUSCA_PROVEEDOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoProveedor", DbType="VarChar(100)")] string codigoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor, codigoProveedor, idTipoProveedor, nombre, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_PROVEEDORResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_BUSCA_PRODUCTO")]
		public ISingleResult<SP_BUSCA_PRODUCTOResult> SP_BUSCA_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Decimal(18,0)")] System.Nullable<decimal> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoProducto", DbType="VarChar(100)")] string codigoProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAlmacen", DbType="Decimal(18,0)")] System.Nullable<decimal> idAlmacen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoEmpaque", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoEmpaque, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProducto", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaEntradaDesde", DbType="Date")] System.Nullable<System.DateTime> fechaEntradaDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaEntradaHasta", DbType="Date")] System.Nullable<System.DateTime> fechaEntradaHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, codigoProducto, idAlmacen, idTipoProveedor, idProveedor, idTipoEmpaque, idTipoProducto, descripcion, fechaEntradaDesde, fechaEntradaHasta, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_BUSCA_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_MANTENIMIENTO_PRODUCTO")]
		public ISingleResult<SP_MANTENIMIENTO_PRODUCTOResult> SP_MANTENIMIENTO_PRODUCTO(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Decimal(18,0)")] System.Nullable<decimal> idProducto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoProducto", DbType="VarChar(100)")] string codigoProducto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAlmacen", DbType="Decimal(18,0)")] System.Nullable<decimal> idAlmacen, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProveedor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idProveedor, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoEmpaque", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoEmpaque, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProducto", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProducto, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estatus", DbType="Bit")] System.Nullable<bool> estatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadAlmacen", DbType="Int")] System.Nullable<int> cantidadAlmacen, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioCompra", DbType="Decimal(20,2)")] System.Nullable<decimal> precioCompra, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioVenta", DbType="Decimal(20,2)")] System.Nullable<decimal> precioVenta, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoPrecio", DbType="Decimal(20,2)")] System.Nullable<decimal> segundoPrecio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TercerPrecio", DbType="Decimal(20,2)")] System.Nullable<decimal> tercerPrecio, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LlevaDescuento", DbType="Bit")] System.Nullable<bool> llevaDescuento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PorcientoDescuento", DbType="Int")] System.Nullable<int> porcientoDescuento, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUsuario", DbType="Decimal(18,0)")] System.Nullable<decimal> idUsuario, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Accion", DbType="VarChar(150)")] string accion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, codigoProducto, idAlmacen, idTipoProveedor, idProveedor, idTipoEmpaque, idTipoProducto, descripcion, estatus, cantidadAlmacen, precioCompra, precioVenta, segundoPrecio, tercerPrecio, llevaDescuento, porcientoDescuento, idUsuario, accion);
			return ((ISingleResult<SP_MANTENIMIENTO_PRODUCTOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Inventario.SP_CONTAR_CANTIDAD_PRODUCTO")]
		public ISingleResult<SP_CONTAR_CANTIDAD_PRODUCTOResult> SP_CONTAR_CANTIDAD_PRODUCTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Decimal(18,0)")] System.Nullable<decimal> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CodigoProducto", DbType="VarChar(100)")] string codigoProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdAlmacen", DbType="Decimal(18,0)")] System.Nullable<decimal> idAlmacen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProveedor", DbType="Decimal(18,0)")] System.Nullable<decimal> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoEmpaque", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoEmpaque, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdTipoProducto", DbType="Decimal(18,0)")] System.Nullable<decimal> idTipoProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaEntradaDesde", DbType="Date")] System.Nullable<System.DateTime> fechaEntradaDesde, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaEntradaHasta", DbType="Date")] System.Nullable<System.DateTime> fechaEntradaHasta, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroPagina", DbType="Int")] System.Nullable<int> numeroPagina, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NumeroRegistros", DbType="Int")] System.Nullable<int> numeroRegistros)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, codigoProducto, idAlmacen, idTipoProveedor, idProveedor, idTipoEmpaque, idTipoProducto, descripcion, fechaEntradaDesde, fechaEntradaHasta, numeroPagina, numeroRegistros);
			return ((ISingleResult<SP_CONTAR_CANTIDAD_PRODUCTOResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_BUSCA_ALMACENResult
	{
		
		private decimal _IdAlmacen;
		
		private string _CodigoAlmacen;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_ALMACENResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlmacen", DbType="Decimal(18,0) NOT NULL")]
		public decimal IdAlmacen
		{
			get
			{
				return this._IdAlmacen;
			}
			set
			{
				if ((this._IdAlmacen != value))
				{
					this._IdAlmacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoAlmacen", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CodigoAlmacen
		{
			get
			{
				return this._CodigoAlmacen;
			}
			set
			{
				if ((this._CodigoAlmacen != value))
				{
					this._CodigoAlmacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(50)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_ALMACENResult
	{
		
		private System.Nullable<decimal> _IdAlmacen;
		
		private string _CodigoAlmacen;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_ALMACENResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlmacen", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdAlmacen
		{
			get
			{
				return this._IdAlmacen;
			}
			set
			{
				if ((this._IdAlmacen != value))
				{
					this._IdAlmacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoAlmacen", DbType="VarChar(100)")]
		public string CodigoAlmacen
		{
			get
			{
				return this._CodigoAlmacen;
			}
			set
			{
				if ((this._CodigoAlmacen != value))
				{
					this._CodigoAlmacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(100)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_TIPO_PROVEEDORResult
	{
		
		private decimal _IdTipoProveedor;
		
		private string _CodigoTipoProveedor;
		
		private string _TipoProveedor;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_TIPO_PROVEEDORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProveedor", DbType="Decimal(18,0) NOT NULL")]
		public decimal IdTipoProveedor
		{
			get
			{
				return this._IdTipoProveedor;
			}
			set
			{
				if ((this._IdTipoProveedor != value))
				{
					this._IdTipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoProveedor", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CodigoTipoProveedor
		{
			get
			{
				return this._CodigoTipoProveedor;
			}
			set
			{
				if ((this._CodigoTipoProveedor != value))
				{
					this._CodigoTipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProveedor", DbType="VarChar(100)")]
		public string TipoProveedor
		{
			get
			{
				return this._TipoProveedor;
			}
			set
			{
				if ((this._TipoProveedor != value))
				{
					this._TipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_PROVEEDORResult
	{
		
		private System.Nullable<decimal> _IdProveedor;
		
		private string _CodigoProveedor;
		
		private System.Nullable<decimal> _IdTipoProveedor;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefonos;
		
		private string _Fax;
		
		private string _Contacto;
		
		private System.Nullable<bool> _LlevaComision;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_PROVEEDORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProveedor", DbType="VarChar(100)")]
		public string CodigoProveedor
		{
			get
			{
				return this._CodigoProveedor;
			}
			set
			{
				if ((this._CodigoProveedor != value))
				{
					this._CodigoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProveedor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoProveedor
		{
			get
			{
				return this._IdTipoProveedor;
			}
			set
			{
				if ((this._IdTipoProveedor != value))
				{
					this._IdTipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonos", DbType="VarChar(100)")]
		public string Telefonos
		{
			get
			{
				return this._Telefonos;
			}
			set
			{
				if ((this._Telefonos != value))
				{
					this._Telefonos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="VarChar(70)")]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this._Contacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LlevaComision", DbType="Bit")]
		public System.Nullable<bool> LlevaComision
		{
			get
			{
				return this._LlevaComision;
			}
			set
			{
				if ((this._LlevaComision != value))
				{
					this._LlevaComision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_TIPO_EMPAQUEResult
	{
		
		private System.Nullable<decimal> _IdTipoEmpaque;
		
		private string _CodigoTipoEmpaque;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_TIPO_EMPAQUEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEmpaque", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoEmpaque
		{
			get
			{
				return this._IdTipoEmpaque;
			}
			set
			{
				if ((this._IdTipoEmpaque != value))
				{
					this._IdTipoEmpaque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoEmpaque", DbType="VarChar(100)")]
		public string CodigoTipoEmpaque
		{
			get
			{
				return this._CodigoTipoEmpaque;
			}
			set
			{
				if ((this._CodigoTipoEmpaque != value))
				{
					this._CodigoTipoEmpaque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_TIPO_EMPAQUEResult
	{
		
		private decimal _IdTipoEmpaque;
		
		private string _CodigoTipoEmpaque;
		
		private string _TipoEmpaque;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_TIPO_EMPAQUEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEmpaque", DbType="Decimal(18,0) NOT NULL")]
		public decimal IdTipoEmpaque
		{
			get
			{
				return this._IdTipoEmpaque;
			}
			set
			{
				if ((this._IdTipoEmpaque != value))
				{
					this._IdTipoEmpaque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoEmpaque", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CodigoTipoEmpaque
		{
			get
			{
				return this._CodigoTipoEmpaque;
			}
			set
			{
				if ((this._CodigoTipoEmpaque != value))
				{
					this._CodigoTipoEmpaque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEmpaque", DbType="VarChar(100)")]
		public string TipoEmpaque
		{
			get
			{
				return this._TipoEmpaque;
			}
			set
			{
				if ((this._TipoEmpaque != value))
				{
					this._TipoEmpaque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_TIPO_PRODUCTOResult
	{
		
		private decimal _IdTipoProducto;
		
		private string _CodigoTipoProducto;
		
		private string _TipoProducto;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_TIPO_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProducto", DbType="Decimal(18,0) NOT NULL")]
		public decimal IdTipoProducto
		{
			get
			{
				return this._IdTipoProducto;
			}
			set
			{
				if ((this._IdTipoProducto != value))
				{
					this._IdTipoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoProducto", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CodigoTipoProducto
		{
			get
			{
				return this._CodigoTipoProducto;
			}
			set
			{
				if ((this._CodigoTipoProducto != value))
				{
					this._CodigoTipoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProducto", DbType="VarChar(100)")]
		public string TipoProducto
		{
			get
			{
				return this._TipoProducto;
			}
			set
			{
				if ((this._TipoProducto != value))
				{
					this._TipoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_TIPO_PRODUCTOResult
	{
		
		private System.Nullable<decimal> _IdTipoProducto;
		
		private string _CodigoTipoProducto;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_TIPO_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProducto", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoProducto
		{
			get
			{
				return this._IdTipoProducto;
			}
			set
			{
				if ((this._IdTipoProducto != value))
				{
					this._IdTipoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoProducto", DbType="VarChar(100)")]
		public string CodigoTipoProducto
		{
			get
			{
				return this._CodigoTipoProducto;
			}
			set
			{
				if ((this._CodigoTipoProducto != value))
				{
					this._CodigoTipoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_TIPO_PROVEEDORResult
	{
		
		private System.Nullable<decimal> _IdTipoProveedor;
		
		private string _CodigoTipoProveedor;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_TIPO_PROVEEDORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProveedor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoProveedor
		{
			get
			{
				return this._IdTipoProveedor;
			}
			set
			{
				if ((this._IdTipoProveedor != value))
				{
					this._IdTipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoTipoProveedor", DbType="VarChar(100)")]
		public string CodigoTipoProveedor
		{
			get
			{
				return this._CodigoTipoProveedor;
			}
			set
			{
				if ((this._CodigoTipoProveedor != value))
				{
					this._CodigoTipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_PROVEEDORResult
	{
		
		private System.Nullable<decimal> _IdProveedor;
		
		private string _CodigoProveedor;
		
		private System.Nullable<decimal> _IdTipoProveedor;
		
		private string _TipoProveedor;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private string _Telefonos;
		
		private string _Fax;
		
		private string _Contacto;
		
		private System.Nullable<bool> _LlevaComision0;
		
		private string _LlevaComision;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_PROVEEDORResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProveedor", DbType="VarChar(100)")]
		public string CodigoProveedor
		{
			get
			{
				return this._CodigoProveedor;
			}
			set
			{
				if ((this._CodigoProveedor != value))
				{
					this._CodigoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProveedor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoProveedor
		{
			get
			{
				return this._IdTipoProveedor;
			}
			set
			{
				if ((this._IdTipoProveedor != value))
				{
					this._IdTipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProveedor", DbType="VarChar(100)")]
		public string TipoProveedor
		{
			get
			{
				return this._TipoProveedor;
			}
			set
			{
				if ((this._TipoProveedor != value))
				{
					this._TipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(8000)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefonos", DbType="VarChar(100)")]
		public string Telefonos
		{
			get
			{
				return this._Telefonos;
			}
			set
			{
				if ((this._Telefonos != value))
				{
					this._Telefonos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(20)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contacto", DbType="VarChar(70)")]
		public string Contacto
		{
			get
			{
				return this._Contacto;
			}
			set
			{
				if ((this._Contacto != value))
				{
					this._Contacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LlevaComision0", DbType="Bit")]
		public System.Nullable<bool> LlevaComision0
		{
			get
			{
				return this._LlevaComision0;
			}
			set
			{
				if ((this._LlevaComision0 != value))
				{
					this._LlevaComision0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LlevaComision", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string LlevaComision
		{
			get
			{
				return this._LlevaComision;
			}
			set
			{
				if ((this._LlevaComision != value))
				{
					this._LlevaComision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_BUSCA_PRODUCTOResult
	{
		
		private System.Nullable<decimal> _IdProducto;
		
		private string _CodigoProducto;
		
		private System.Nullable<decimal> _IdAlmacen;
		
		private string _Almacen;
		
		private System.Nullable<decimal> _IdTipoProveedor;
		
		private string _TipoProveedor;
		
		private System.Nullable<decimal> _IdProveedor;
		
		private string _Proveedor;
		
		private System.Nullable<decimal> _IdTipoEmpaque;
		
		private string _TipoEmpaque;
		
		private System.Nullable<decimal> _IdTipoProducto0;
		
		private string _TipoProducto;
		
		private string _Producto;
		
		private System.Nullable<bool> _Estatus0;
		
		private string _Estatus;
		
		private System.Nullable<int> _CantidadAlmacen;
		
		private System.Nullable<decimal> _PrecioCompra;
		
		private System.Nullable<decimal> _PrecioVenta;
		
		private System.Nullable<decimal> _SegundoPrecio;
		
		private System.Nullable<decimal> _TercerPrecio;
		
		private System.Nullable<System.DateTime> _FechaEntrada0;
		
		private string _FechaEntrada;
		
		private System.Nullable<bool> _LlevaDescuento0;
		
		private string _LlevaDescuento;
		
		private System.Nullable<int> _PorcientoDescuento;
		
		private System.Nullable<decimal> _UsuarioAdiciona;
		
		private string _CreadoPor;
		
		private System.Nullable<System.DateTime> _FechaAdiciona0;
		
		private string _FechaAdiciona;
		
		private System.Nullable<decimal> _UsuarioModifica;
		
		private string _ModificadoPor;
		
		private System.Nullable<System.DateTime> _FechaModifica0;
		
		private string _FechaModifica;
		
		public SP_BUSCA_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProducto", DbType="VarChar(100)")]
		public string CodigoProducto
		{
			get
			{
				return this._CodigoProducto;
			}
			set
			{
				if ((this._CodigoProducto != value))
				{
					this._CodigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlmacen", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdAlmacen
		{
			get
			{
				return this._IdAlmacen;
			}
			set
			{
				if ((this._IdAlmacen != value))
				{
					this._IdAlmacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Almacen", DbType="VarChar(100)")]
		public string Almacen
		{
			get
			{
				return this._Almacen;
			}
			set
			{
				if ((this._Almacen != value))
				{
					this._Almacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProveedor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoProveedor
		{
			get
			{
				return this._IdTipoProveedor;
			}
			set
			{
				if ((this._IdTipoProveedor != value))
				{
					this._IdTipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProveedor", DbType="VarChar(100)")]
		public string TipoProveedor
		{
			get
			{
				return this._TipoProveedor;
			}
			set
			{
				if ((this._TipoProveedor != value))
				{
					this._TipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proveedor", DbType="VarChar(100)")]
		public string Proveedor
		{
			get
			{
				return this._Proveedor;
			}
			set
			{
				if ((this._Proveedor != value))
				{
					this._Proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEmpaque", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoEmpaque
		{
			get
			{
				return this._IdTipoEmpaque;
			}
			set
			{
				if ((this._IdTipoEmpaque != value))
				{
					this._IdTipoEmpaque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEmpaque", DbType="VarChar(100)")]
		public string TipoEmpaque
		{
			get
			{
				return this._TipoEmpaque;
			}
			set
			{
				if ((this._TipoEmpaque != value))
				{
					this._TipoEmpaque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProducto0", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoProducto0
		{
			get
			{
				return this._IdTipoProducto0;
			}
			set
			{
				if ((this._IdTipoProducto0 != value))
				{
					this._IdTipoProducto0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProducto", DbType="VarChar(100)")]
		public string TipoProducto
		{
			get
			{
				return this._TipoProducto;
			}
			set
			{
				if ((this._TipoProducto != value))
				{
					this._TipoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="VarChar(100)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus0", DbType="Bit")]
		public System.Nullable<bool> Estatus0
		{
			get
			{
				return this._Estatus0;
			}
			set
			{
				if ((this._Estatus0 != value))
				{
					this._Estatus0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadAlmacen", DbType="Int")]
		public System.Nullable<int> CantidadAlmacen
		{
			get
			{
				return this._CantidadAlmacen;
			}
			set
			{
				if ((this._CantidadAlmacen != value))
				{
					this._CantidadAlmacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioCompra", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioCompra
		{
			get
			{
				return this._PrecioCompra;
			}
			set
			{
				if ((this._PrecioCompra != value))
				{
					this._PrecioCompra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVenta", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioVenta
		{
			get
			{
				return this._PrecioVenta;
			}
			set
			{
				if ((this._PrecioVenta != value))
				{
					this._PrecioVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoPrecio", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> SegundoPrecio
		{
			get
			{
				return this._SegundoPrecio;
			}
			set
			{
				if ((this._SegundoPrecio != value))
				{
					this._SegundoPrecio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TercerPrecio", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> TercerPrecio
		{
			get
			{
				return this._TercerPrecio;
			}
			set
			{
				if ((this._TercerPrecio != value))
				{
					this._TercerPrecio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntrada0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaEntrada0
		{
			get
			{
				return this._FechaEntrada0;
			}
			set
			{
				if ((this._FechaEntrada0 != value))
				{
					this._FechaEntrada0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntrada", DbType="NVarChar(30)")]
		public string FechaEntrada
		{
			get
			{
				return this._FechaEntrada;
			}
			set
			{
				if ((this._FechaEntrada != value))
				{
					this._FechaEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LlevaDescuento0", DbType="Bit")]
		public System.Nullable<bool> LlevaDescuento0
		{
			get
			{
				return this._LlevaDescuento0;
			}
			set
			{
				if ((this._LlevaDescuento0 != value))
				{
					this._LlevaDescuento0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LlevaDescuento", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string LlevaDescuento
		{
			get
			{
				return this._LlevaDescuento;
			}
			set
			{
				if ((this._LlevaDescuento != value))
				{
					this._LlevaDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcientoDescuento", DbType="Int")]
		public System.Nullable<int> PorcientoDescuento
		{
			get
			{
				return this._PorcientoDescuento;
			}
			set
			{
				if ((this._PorcientoDescuento != value))
				{
					this._PorcientoDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(1000)")]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this._CreadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona0
		{
			get
			{
				return this._FechaAdiciona0;
			}
			set
			{
				if ((this._FechaAdiciona0 != value))
				{
					this._FechaAdiciona0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="NVarChar(30)")]
		public string FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(1000)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this._ModificadoPor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica0", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica0
		{
			get
			{
				return this._FechaModifica0;
			}
			set
			{
				if ((this._FechaModifica0 != value))
				{
					this._FechaModifica0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="NVarChar(30)")]
		public string FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_MANTENIMIENTO_PRODUCTOResult
	{
		
		private System.Nullable<decimal> _IdProducto;
		
		private string _CodigoProducto;
		
		private System.Nullable<decimal> _IdAlmacen;
		
		private System.Nullable<decimal> _IdTipoProveedor;
		
		private System.Nullable<decimal> _IdProveedor;
		
		private System.Nullable<decimal> _IdTipoEmpaque;
		
		private System.Nullable<decimal> _IdTipoProducto;
		
		private string _Descripcion;
		
		private System.Nullable<bool> _Estatus;
		
		private System.Nullable<int> _CantidadAlmacen;
		
		private System.Nullable<decimal> _PrecioCompra;
		
		private System.Nullable<decimal> _PrecioVenta;
		
		private System.Nullable<decimal> _SegundoPrecio;
		
		private System.Nullable<decimal> _TercerPrecio;
		
		private System.Nullable<System.DateTime> _FechaEntrada;
		
		private System.Nullable<bool> _LlevaDescuento;
		
		private System.Nullable<int> _PorcientoDescuento;
		
		private System.Nullable<int> _UsuarioAdiciona;
		
		private System.Nullable<System.DateTime> _FechaAdiciona;
		
		private System.Nullable<int> _UsuarioModifica;
		
		private System.Nullable<System.DateTime> _FechaModifica;
		
		public SP_MANTENIMIENTO_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoProducto", DbType="VarChar(100)")]
		public string CodigoProducto
		{
			get
			{
				return this._CodigoProducto;
			}
			set
			{
				if ((this._CodigoProducto != value))
				{
					this._CodigoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlmacen", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdAlmacen
		{
			get
			{
				return this._IdAlmacen;
			}
			set
			{
				if ((this._IdAlmacen != value))
				{
					this._IdAlmacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProveedor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoProveedor
		{
			get
			{
				return this._IdTipoProveedor;
			}
			set
			{
				if ((this._IdTipoProveedor != value))
				{
					this._IdTipoProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoEmpaque", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoEmpaque
		{
			get
			{
				return this._IdTipoEmpaque;
			}
			set
			{
				if ((this._IdTipoEmpaque != value))
				{
					this._IdTipoEmpaque = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoProducto", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> IdTipoProducto
		{
			get
			{
				return this._IdTipoProducto;
			}
			set
			{
				if ((this._IdTipoProducto != value))
				{
					this._IdTipoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(100)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Bit")]
		public System.Nullable<bool> Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this._Estatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadAlmacen", DbType="Int")]
		public System.Nullable<int> CantidadAlmacen
		{
			get
			{
				return this._CantidadAlmacen;
			}
			set
			{
				if ((this._CantidadAlmacen != value))
				{
					this._CantidadAlmacen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioCompra", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioCompra
		{
			get
			{
				return this._PrecioCompra;
			}
			set
			{
				if ((this._PrecioCompra != value))
				{
					this._PrecioCompra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVenta", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> PrecioVenta
		{
			get
			{
				return this._PrecioVenta;
			}
			set
			{
				if ((this._PrecioVenta != value))
				{
					this._PrecioVenta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoPrecio", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> SegundoPrecio
		{
			get
			{
				return this._SegundoPrecio;
			}
			set
			{
				if ((this._SegundoPrecio != value))
				{
					this._SegundoPrecio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TercerPrecio", DbType="Decimal(20,2)")]
		public System.Nullable<decimal> TercerPrecio
		{
			get
			{
				return this._TercerPrecio;
			}
			set
			{
				if ((this._TercerPrecio != value))
				{
					this._TercerPrecio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntrada", DbType="Date")]
		public System.Nullable<System.DateTime> FechaEntrada
		{
			get
			{
				return this._FechaEntrada;
			}
			set
			{
				if ((this._FechaEntrada != value))
				{
					this._FechaEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LlevaDescuento", DbType="Bit")]
		public System.Nullable<bool> LlevaDescuento
		{
			get
			{
				return this._LlevaDescuento;
			}
			set
			{
				if ((this._LlevaDescuento != value))
				{
					this._LlevaDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PorcientoDescuento", DbType="Int")]
		public System.Nullable<int> PorcientoDescuento
		{
			get
			{
				return this._PorcientoDescuento;
			}
			set
			{
				if ((this._PorcientoDescuento != value))
				{
					this._PorcientoDescuento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioAdiciona", DbType="Int")]
		public System.Nullable<int> UsuarioAdiciona
		{
			get
			{
				return this._UsuarioAdiciona;
			}
			set
			{
				if ((this._UsuarioAdiciona != value))
				{
					this._UsuarioAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAdiciona", DbType="Date")]
		public System.Nullable<System.DateTime> FechaAdiciona
		{
			get
			{
				return this._FechaAdiciona;
			}
			set
			{
				if ((this._FechaAdiciona != value))
				{
					this._FechaAdiciona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioModifica", DbType="Int")]
		public System.Nullable<int> UsuarioModifica
		{
			get
			{
				return this._UsuarioModifica;
			}
			set
			{
				if ((this._UsuarioModifica != value))
				{
					this._UsuarioModifica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModifica", DbType="Date")]
		public System.Nullable<System.DateTime> FechaModifica
		{
			get
			{
				return this._FechaModifica;
			}
			set
			{
				if ((this._FechaModifica != value))
				{
					this._FechaModifica = value;
				}
			}
		}
	}
	
	public partial class SP_CONTAR_CANTIDAD_PRODUCTOResult
	{
		
		private System.Nullable<int> _Cantidad;
		
		public SP_CONTAR_CANTIDAD_PRODUCTOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
