<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaFacturacionMedico" Class="BDInventarioDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JUANMARCELINOMD;Initial Catalog=SistemaFacturacionMedico;User ID=sa" SettingsObjectName="DSSistemaPuntoVentaClinico.Data.Properties.Settings" SettingsPropertyName="SistemaFacturacionMedicoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="Inventario.SP_BUSCA_ALMACEN" Method="SP_BUSCA_ALMACEN">
    <Parameter Name="IdAlmacen" Parameter="idAlmacen" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoAlmacen" Parameter="codigoAlmacen" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_ALMACENResult">
      <Column Name="IdAlmacen" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoAlmacen" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_MANTENIMIENTO_ALMACEN" Method="SP_MANTENIMIENTO_ALMACEN">
    <Parameter Name="IdAlmacen" Parameter="idAlmacen" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoAlmacen" Parameter="codigoAlmacen" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_ALMACENResult">
      <Column Name="IdAlmacen" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoAlmacen" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_BUSCA_TIPO_PROVEEDOR" Method="SP_BUSCA_TIPO_PROVEEDOR">
    <Parameter Name="IdTipoProveedor" Parameter="idTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoTipoProveedor" Parameter="codigoTipoProveedor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_PROVEEDORResult">
      <Column Name="IdTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoTipoProveedor" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TipoProveedor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_MANTENIMIENTO_PROVEEDOR" Method="SP_MANTENIMIENTO_PROVEEDOR">
    <Parameter Name="IdProveedor" Parameter="idProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoProveedor" Parameter="codigoProveedor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoProveedor" Parameter="idTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Telefonos" Parameter="telefonos" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Fax" Parameter="fax" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Contacto" Parameter="contacto" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="LlevaComision" Parameter="llevaComision" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_PROVEEDORResult">
      <Column Name="IdProveedor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoProveedor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Contacto" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="LlevaComision" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_MANTENIMIENTO_TIPO_EMPAQUE" Method="SP_MANTENIMIENTO_TIPO_EMPAQUE">
    <Parameter Name="IdTipoEmpaque" Parameter="idTipoEmpaque" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoTipoEmpaque" Parameter="codigoTipoEmpaque" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_TIPO_EMPAQUEResult">
      <Column Name="IdTipoEmpaque" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoTipoEmpaque" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_BUSCA_TIPO_EMPAQUE" Method="SP_BUSCA_TIPO_EMPAQUE">
    <Parameter Name="IdTipoEmpaque" Parameter="idTipoEmpaque" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoTipoEmpaque" Parameter="codigoTipoEmpaque" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_EMPAQUEResult">
      <Column Name="IdTipoEmpaque" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoTipoEmpaque" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TipoEmpaque" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_BUSCA_TIPO_PRODUCTO" Method="SP_BUSCA_TIPO_PRODUCTO">
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoTipoProducto" Parameter="codigoTipoProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_TIPO_PRODUCTOResult">
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoTipoProducto" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_MANTENIMIENTO_TIPO_PRODUCTO" Method="SP_MANTENIMIENTO_TIPO_PRODUCTO">
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoTipoProducto" Parameter="codigoTipoProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_TIPO_PRODUCTOResult">
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoTipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_MANTENIMIENTO_TIPO_PROVEEDOR" Method="SP_MANTENIMIENTO_TIPO_PROVEEDOR">
    <Parameter Name="IdTipoProveedor" Parameter="idTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoTipoProveedor" Parameter="codigoTipoProveedor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_TIPO_PROVEEDORResult">
      <Column Name="IdTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoTipoProveedor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_BUSCA_PROVEEDOR" Method="SP_BUSCA_PROVEEDOR">
    <Parameter Name="IdProveedor" Parameter="idProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoProveedor" Parameter="codigoProveedor" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdTipoProveedor" Parameter="idTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_PROVEEDORResult">
      <Column Name="IdProveedor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoProveedor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TipoProveedor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Telefonos" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Contacto" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="LlevaComision0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LlevaComision" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_BUSCA_PRODUCTO" Method="SP_BUSCA_PRODUCTO">
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoProducto" Parameter="codigoProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdAlmacen" Parameter="idAlmacen" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdTipoProveedor" Parameter="idTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdProveedor" Parameter="idProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdTipoEmpaque" Parameter="idTipoEmpaque" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaEntradaDesde" Parameter="fechaEntradaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaEntradaHasta" Parameter="fechaEntradaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_PRODUCTOResult">
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdAlmacen" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Almacen" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TipoProveedor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Proveedor" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoEmpaque" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TipoEmpaque" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdTipoProducto0" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TipoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Producto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadAlmacen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="SegundoPrecio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TercerPrecio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaEntrada0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaEntrada" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="LlevaDescuento0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LlevaDescuento" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="PorcientoDescuento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_MANTENIMIENTO_PRODUCTO" Method="SP_MANTENIMIENTO_PRODUCTO">
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoProducto" Parameter="codigoProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdAlmacen" Parameter="idAlmacen" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdTipoProveedor" Parameter="idTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdProveedor" Parameter="idProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdTipoEmpaque" Parameter="idTipoEmpaque" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="CantidadAlmacen" Parameter="cantidadAlmacen" Type="System.Int32" DbType="Int" />
    <Parameter Name="PrecioCompra" Parameter="precioCompra" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="PrecioVenta" Parameter="precioVenta" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="SegundoPrecio" Parameter="segundoPrecio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="TercerPrecio" Parameter="tercerPrecio" Type="System.Decimal" DbType="Decimal(20,2)" />
    <Parameter Name="LlevaDescuento" Parameter="llevaDescuento" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="PorcientoDescuento" Parameter="porcientoDescuento" Type="System.Int32" DbType="Int" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_PRODUCTOResult">
      <Column Name="IdProducto" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CodigoProducto" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdAlmacen" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdProveedor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdTipoEmpaque" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdTipoProducto" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CantidadAlmacen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrecioCompra" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="PrecioVenta" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="SegundoPrecio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="TercerPrecio" Type="System.Decimal" DbType="Decimal(20,2)" CanBeNull="true" />
      <Column Name="FechaEntrada" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LlevaDescuento" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PorcientoDescuento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Inventario.SP_CONTAR_CANTIDAD_PRODUCTO" Method="SP_CONTAR_CANTIDAD_PRODUCTO">
    <Parameter Name="IdProducto" Parameter="idProducto" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoProducto" Parameter="codigoProducto" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdAlmacen" Parameter="idAlmacen" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdTipoProveedor" Parameter="idTipoProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdProveedor" Parameter="idProveedor" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdTipoEmpaque" Parameter="idTipoEmpaque" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdTipoProducto" Parameter="idTipoProducto" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Descripcion" Parameter="descripcion" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FechaEntradaDesde" Parameter="fechaEntradaDesde" Type="System.DateTime" DbType="Date" />
    <Parameter Name="FechaEntradaHasta" Parameter="fechaEntradaHasta" Type="System.DateTime" DbType="Date" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_CONTAR_CANTIDAD_PRODUCTOResult">
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>