<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaFacturacionMedico" Class="BDSeguridadDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JUANMARCELINOMD;Initial Catalog=SistemaFacturacionMedico;User ID=sa" SettingsObjectName="DSSistemaPuntoVentaClinico.Data.Properties.Settings" SettingsPropertyName="SistemaFacturacionMedicoConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="Seguridad.SP_BUSCA_USUARIOS" Method="SP_BUSCA_USUARIOS">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CodigoUsuario" Parameter="codigoUsuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdPerfil" Parameter="idPerfil" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="UsuarioLogin" Parameter="usuarioLogin" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Clave" Parameter="clave" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_USUARIOSResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CodigoUsuario" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IdPerfil" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Perfil" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Persona" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Seguridad.SP_BUSCAR_EJECUTAR_USUARIO" Method="SP_BUSCAR_EJECUTAR_USUARIO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <ElementType Name="SP_BUSCAR_EJECUTAR_USUARIOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="CantidadIntentos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Seguridad.SP_MANTENIMINTO_EJECUTAR_USUARIO" Method="SP_MANTENIMINTO_EJECUTAR_USUARIO">
    <Parameter Name="IdRegistro" Parameter="idRegistro" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="CantidadIntentos" Parameter="cantidadIntentos" Type="System.Int32" DbType="Int" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMINTO_EJECUTAR_USUARIOResult">
      <Column Name="IdRegistro" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CantidadIntentos" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Seguridad.SP_MANTENIMIENTO_CLAVE_SEGURIDAD" Method="SP_MANTENIMIENTO_CLAVE_SEGURIDAD">
    <Parameter Name="IdClaveSeguridad" Parameter="idClaveSeguridad" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Clave" Parameter="clave" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdUsuarioCrea" Parameter="idUsuarioCrea" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_CLAVE_SEGURIDADResult">
      <Column Name="IdClaveSeguridad" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Seguridad.SP_BUSCA_CLAVE_SEGURIDAD" Method="SP_BUSCA_CLAVE_SEGURIDAD">
    <Parameter Name="ClaveSeguridad" Parameter="claveSeguridad" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="NumeroPagina" Parameter="numeroPagina" Type="System.Int32" DbType="Int" />
    <Parameter Name="NumeroRegistros" Parameter="numeroRegistros" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCA_CLAVE_SEGURIDADResult">
      <Column Name="IdClaveSeguridad" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Persona" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Perfil" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Estatus0" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Estatus" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaAdiciona0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ModificadoPor" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="FechaModifica0" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Seguridad.SP_SACAR_LOGON_BD" Method="SP_SACAR_LOGON_BD">
    <Parameter Name="IdLogonBD" Parameter="idLogonBD" Type="System.Decimal" DbType="Decimal(20,0)" />
    <ElementType Name="SP_SACAR_LOGON_BDResult">
      <Column Name="IdLogonBd" Type="System.Decimal" DbType="Decimal(20,0) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="Seguridad.SP_MANTENIMIENTO_USUARIO" Method="SP_MANTENIMIENTO_USUARIO">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="CodigoUsuario" Parameter="codigoUsuario" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="IdPerfil" Parameter="idPerfil" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Usuario" Parameter="usuario" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="Clave" Parameter="clave" Type="System.String" DbType="VarChar(8000)" />
    <Parameter Name="Persona" Parameter="persona" Type="System.String" DbType="VarChar(1000)" />
    <Parameter Name="Estatus" Parameter="estatus" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="IdusuarioCrea" Parameter="idusuarioCrea" Type="System.Decimal" DbType="Decimal(20,0)" />
    <Parameter Name="Accion" Parameter="accion" Type="System.String" DbType="VarChar(150)" />
    <ElementType Name="SP_MANTENIMIENTO_USUARIOResult">
      <Column Name="IdUsuario" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="CodigoUsuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="IdPerfil" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="Usuario" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="Persona" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Estatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UsuarioAdiciona" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaAdiciona" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsuarioModifica" Type="System.Decimal" DbType="Decimal(20,0)" CanBeNull="true" />
      <Column Name="FechaModifica" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>